public class Fetchmbadata2 {

    public PageReference showReport() {
        return null;
    }
    Public List<Decimal> data {get; set;}


    public string monthSelected { get; set; }
    public DateTime fromdate{get; set;}
    public DateTime todate{get; set;}
    
    public boolean dateformat{get;set;}
    
    
    
    public String  selectValue{get;set;}
    Public String convselectvalue;
    
    public String rounded6{get;set;}
    public String rounded5{get;set;}
    public String rounded4{get;set;}
    public String rounded3{get;set;}
    public String rounded2{get;set;}
    public String rounded1{get;set;}
    public String rounded{get;set;}

    public String rounded7{get;set;}
    public String rounded8{get;set;}
    public String rounded9{get;set;}
    public String rounded10{get;set;}
    public String rounded11{get;set;}
    public String rounded12{get;set;}
    public String rounded13{get;set;}
    
    public Decimal Quote_submitted{get;set;}
    public Decimal Still_active{get;set;}
    public Decimal Oppurtunity_on_hold{get;set;}
    public Decimal Projects_shelved{get;set;}
    public Decimal Awarded_PO_by_customer{get;set;}
    public Decimal Order_won{get;set;}
    public Decimal Lost_on_Cost{get;set;}
    public Decimal Lost_on_Lead_time{get;set;}   
    public Decimal Lost_on_strategic_reasons{get;set;}
    public Decimal Regret{get;set;}
    public Decimal Overall{get;set;}
    public Decimal Overall1{get;set;}
     
     public Decimal PerQuote_submitted{get;set;}
    public Decimal PerStill_active{get;set;}
    public Decimal PerOppurtunity_on_hold{get;set;}
    public Decimal PerProjects_shelved{get;set;}
    public Decimal PerAwarded_PO_by_customer{get;set;}
    public Decimal PerOrder_won{get;set;}
    public Decimal PerLost_on_Cost{get;set;}
    public Decimal PerLost_on_Lead_time{get;set;}   
    public Decimal PerLost_on_strategic_reasons{get;set;}
    public Decimal PerRegret{get;set;}
    
   
    public Decimal OWafunne{get;set;}
    public Decimal OWafunnee{get;set;}
    public Decimal OWrqsub{get;set;}
    public Decimal OWacfqt{get;set;}
    public Decimal OWqtprep{get;set;}
    public Decimal ACafunne{get;set;}
    public Decimal ACafunnee{get;set;}
    public Decimal ACundneg{get;set;}
    public Decimal ACrqsub{get;set;}
    public Decimal ACacfqt{get;set;}
    public Decimal ACqtprep{get;set;}
    public Decimal SAafunne{get;set;}
    public Decimal SAundneg{get;set;}
    public Decimal SArqsub{get;set;}
    public Decimal SAacfqt{get;set;}
    public Decimal SAqtprep{get;set;}
    public Decimal QSafunne{get;set;}
    public Decimal QSundneg{get;set;}
    public Decimal QSrqsub{get;set;}
    public Decimal QSacfqt{get;set;}
    public Decimal QSqtprep{get;set;}
   
    public Decimal OrdersWon{get;set;}
    public Decimal OrderWon0_10{get;set;}
    public Decimal OrderWon10_50{get;set;}
    public Decimal OrderWon51_150{get;set;}
    public Decimal OrderWon151_350{get;set;}
    public Decimal OrderWon351_700{get;set;}
    public Decimal OrderWonGreaterThan700L{get;set;}
    
    public Decimal QuotesSubmitted{get;set;}   
    public Decimal QuotesSubmitted0_10L{get;set;}
    public Decimal QuotesSubmitted10_50L{get;set;}
    public Decimal QuotesSubmitted51_150L{get;set;}
    public Decimal QuotesSubmitted151_350L{get;set;}
    public Decimal QuotesSubmitted351_700L{get;set;}
    public Decimal QuotesSubmittedGreaterThan700L{get;set;}
    
    public Decimal Totalper{get;set;}
    public Decimal per0_10{get;set;}
    public Decimal per10_50{get;set;}
    public Decimal per51_150{get;set;}
    public Decimal per151_350{get;set;}
    public Decimal per351_700{get;set;}
    public Decimal pergtr700{get;set;}
    
    public Decimal NTotalper{get;set;}
    public Decimal Nper0_10{get;set;}
    public Decimal Nper10_50{get;set;}
    public Decimal Nper51_150{get;set;}
    public Decimal Nper151_350{get;set;}
    public Decimal Nper351_700{get;set;}
    public Decimal Npergtr700{get;set;}
    
    public Decimal ExpOrdersWon{get;set;}
    public Decimal ExpOrderWon0_10{get;set;}
    public Decimal ExpOrderWon10_50{get;set;}
    public Decimal ExpOrderWon51_150{get;set;}
    public Decimal ExpOrderWon151_350{get;set;}
    public Decimal ExpOrderWon351_700{get;set;}
    public Decimal ExpOrderWonGreaterThan700L{get;set;}
    
    public Decimal ExpQuotesSubmitted{get;set;}   
    public Decimal ExpQuotesSubmitted0_10L{get;set;}
    public Decimal ExpQuotesSubmitted10_50L{get;set;}
    public Decimal ExpQuotesSubmitted51_150L{get;set;}
    public Decimal ExpQuotesSubmitted151_350L{get;set;}
    public Decimal ExpQuotesSubmitted351_700L{get;set;}
    public Decimal ExpQuotesSubmittedGreaterThan700L{get;set;}
    
    public Decimal ExpTotalper{get;set;}
    public Decimal Expper0_10{get;set;}
    public Decimal Expper10_50{get;set;}
    public Decimal Expper51_150{get;set;}
    public Decimal Expper151_350{get;set;}
    public Decimal Expper351_700{get;set;}
    public Decimal Exppergtr700{get;set;}
    
    public Decimal ExpNTotalper{get;set;}
    public Decimal ExpNper0_10{get;set;}
    public Decimal ExpNper10_50{get;set;}
    public Decimal ExpNper51_150{get;set;}
    public Decimal ExpNper151_350{get;set;}
    public Decimal ExpNper351_700{get;set;}
    public Decimal ExpNpergtr700{get;set;}
    
    
    public Decimal DomOrdersWon{get;set;}
    public Decimal DomOrderWon0_10{get;set;}
    public Decimal DomOrderWon10_50{get;set;}
    public Decimal DomOrderWon51_150{get;set;}
    public Decimal DomOrderWon151_350{get;set;}
    public Decimal DomOrderWon351_700{get;set;}
    public Decimal DomOrderWonGreaterThan700L{get;set;}
    
    public Decimal DomQuotesSubmitted{get;set;}   
    public Decimal DomQuotesSubmitted0_10L{get;set;}
    public Decimal DomQuotesSubmitted10_50L{get;set;}
    public Decimal DomQuotesSubmitted51_150L{get;set;}
    public Decimal DomQuotesSubmitted151_350L{get;set;}
    public Decimal DomQuotesSubmitted351_700L{get;set;}
    public Decimal DomQuotesSubmittedGreaterThan700L{get;set;}
    
    
    public Decimal DomTotalper{get;set;}
    public Decimal Domper0_10{get;set;}
    public Decimal Domper10_50{get;set;}
    public Decimal Domper51_150{get;set;}
    public Decimal Domper151_350{get;set;}
    public Decimal Domper351_700{get;set;}
    public Decimal Dompergtr700{get;set;}
    
    public Decimal DomNTotalper{get;set;}
    public Decimal DomNper0_10{get;set;}
    public Decimal DomNper10_50{get;set;}
    public Decimal DomNper51_150{get;set;}
    public Decimal DomNper151_350{get;set;}
    public Decimal DomNper351_700{get;set;}
    public Decimal DomNpergtr700{get;set;}
    
    
    
    public Decimal ExiOrdersWon{get;set;}
    public Decimal ExiOrderWon0_10{get;set;}
    public Decimal ExiOrderWon10_50{get;set;}
    public Decimal ExiOrderWon51_150{get;set;}
    public Decimal ExiOrderWon151_350{get;set;}
    public Decimal ExiOrderWon351_700{get;set;}
    public Decimal ExiOrderWonGreaterThan700L{get;set;}
    
    public Decimal ExiQuotesSubmitted{get;set;}   
    public Decimal ExiQuotesSubmitted0_10L{get;set;}
    public Decimal ExiQuotesSubmitted10_50L{get;set;}
    public Decimal ExiQuotesSubmitted51_150L{get;set;}
    public Decimal ExiQuotesSubmitted151_350L{get;set;}
    public Decimal ExiQuotesSubmitted351_700L{get;set;}
    public Decimal ExiQuotesSubmittedGreaterThan700L{get;set;}
    
    public Decimal ExiTotalper{get;set;}
    public Decimal Exiper0_10{get;set;}
    public Decimal Exiper10_50{get;set;}
    public Decimal Exiper51_150{get;set;}
    public Decimal Exiper151_350{get;set;}
    public Decimal Exiper351_700{get;set;}
    public Decimal Exipergtr700{get;set;}
    
    public Decimal ExiNTotalper{get;set;}
    public Decimal ExiNper0_10{get;set;}
    public Decimal ExiNper10_50{get;set;}
    public Decimal ExiNper51_150{get;set;}
    public Decimal ExiNper151_350{get;set;}
    public Decimal ExiNper351_700{get;set;}
    public Decimal ExiNpergtr700{get;set;}
    
    
    public Decimal NewOrdersWon{get;set;}
    public Decimal NewOrderWon0_10{get;set;}
    public Decimal NewOrderWon10_50{get;set;}
    public Decimal NewOrderWon51_150{get;set;}
    public Decimal NewOrderWon151_350{get;set;}
    public Decimal NewOrderWon351_700{get;set;}
    public Decimal NewOrderWonGreaterThan700L{get;set;}
    
    public Decimal NewQuotesSubmitted{get;set;}   
    public Decimal NewQuotesSubmitted0_10L{get;set;}
    public Decimal NewQuotesSubmitted10_50L{get;set;}
    public Decimal NewQuotesSubmitted51_150L{get;set;}
    public Decimal NewQuotesSubmitted151_350L{get;set;}
    public Decimal NewQuotesSubmitted351_700L{get;set;}
    public Decimal NewQuotesSubmittedGreaterThan700L{get;set;}
    
    public Decimal NewTotalper{get;set;}
    public Decimal Newper0_10{get;set;}
    public Decimal Newper10_50{get;set;}
    public Decimal Newper51_150{get;set;}
    public Decimal Newper151_350{get;set;}
    public Decimal Newper351_700{get;set;}
    public Decimal Newpergtr700{get;set;}
    
    public Decimal NewNTotalper{get;set;}
    public Decimal NewNper0_10{get;set;}
    public Decimal NewNper10_50{get;set;}
    public Decimal NewNper51_150{get;set;}
    public Decimal NewNper151_350{get;set;}
    public Decimal NewNper351_700{get;set;}
    public Decimal NewNpergtr700{get;set;}
    
    public List<opportunity> oplisttemp{get;set;}
    
    public Decimal TotanNumberOfProjects0_10L{get;set;}
    public Decimal TotanNumberOfProjects10_50L{get;set;}
    public Decimal TotanNumberOfProjects51_150L{get;set;}
    public Decimal TotanNumberOfProjects151_350L{get;set;}
    public Decimal TotanNumberOfProjects351_700L{get;set;}
    public Decimal TotanNumberOfProjectsGreaterThan700L{get;set;}
    
    public Decimal TotanNumberOfProjectsWon0_10L{get;set;}
    public Decimal TotanNumberOfProjectsWon10_50L{get;set;}
    public Decimal TotanNumberOfProjectsWon51_150L{get;set;}
    public Decimal TotanNumberOfProjectsWon151_350L{get;set;}
    public Decimal TotanNumberOfProjectsWon351_700L{get;set;}
    public Decimal TotanNumberOfProjectsWonGreaterThan700L{get;set;}
    
    public Decimal TotanNumberOfProjects{get;set;}
    public Decimal TotanNumberOfProjectsWon{get;set;}
    
    public Decimal ExpTotanNumberOfProjects0_10L{get;set;}
    public Decimal ExpTotanNumberOfProjects10_50L{get;set;}
    public Decimal ExpTotanNumberOfProjects51_150L{get;set;}
    public Decimal ExpTotanNumberOfProjects151_350L{get;set;}
    public Decimal ExpTotanNumberOfProjects351_700L{get;set;}
    public Decimal ExpTotanNumberOfProjectsGreaterThan700L{get;set;}
    
    public Decimal ExpTotanNumberOfProjectsWon0_10L{get;set;}
    public Decimal ExpTotanNumberOfProjectsWon10_50L{get;set;}
    public Decimal ExpTotanNumberOfProjectsWon51_150L{get;set;}
    public Decimal ExpTotanNumberOfProjectsWon151_350L{get;set;}
    public Decimal ExpTotanNumberOfProjectsWon351_700L{get;set;}
    public Decimal ExpTotanNumberOfProjectsWonGreaterThan700L{get;set;}
    
    public Decimal ExpTotanNumberOfProjects{get;set;}
    public Decimal ExpTotanNumberOfProjectsWon{get;set;}
    
    
    public Decimal DomTotanNumberOfProjects0_10L{get;set;}
    public Decimal DomTotanNumberOfProjects10_50L{get;set;}
    public Decimal DomTotanNumberOfProjects51_150L{get;set;}
    public Decimal DomTotanNumberOfProjects151_350L{get;set;}
    public Decimal DomTotanNumberOfProjects351_700L{get;set;}
    public Decimal DomTotanNumberOfProjectsGreaterThan700L{get;set;}
    
    public Decimal DomTotanNumberOfProjectsWon0_10L{get;set;}
    public Decimal DomTotanNumberOfProjectsWon10_50L{get;set;}
    public Decimal DomTotanNumberOfProjectsWon51_150L{get;set;}
    public Decimal DomTotanNumberOfProjectsWon151_350L{get;set;}
    public Decimal DomTotanNumberOfProjectsWon351_700L{get;set;}
    public Decimal DomTotanNumberOfProjectsWonGreaterThan700L{get;set;}
    
    public Decimal DomTotanNumberOfProjects{get;set;}
    public Decimal DomTotanNumberOfProjectsWon{get;set;}
    
    
    public Decimal ExiTotanNumberOfProjects0_10L{get;set;}
    public Decimal ExiTotanNumberOfProjects10_50L{get;set;}
    public Decimal ExiTotanNumberOfProjects51_150L{get;set;}
    public Decimal ExiTotanNumberOfProjects151_350L{get;set;}
    public Decimal ExiTotanNumberOfProjects351_700L{get;set;}
    public Decimal ExiTotanNumberOfProjectsGreaterThan700L{get;set;}
    
    public Decimal ExiTotanNumberOfProjectsWon0_10L{get;set;}
    public Decimal ExiTotanNumberOfProjectsWon10_50L{get;set;}
    public Decimal ExiTotanNumberOfProjectsWon51_150L{get;set;}
    public Decimal ExiTotanNumberOfProjectsWon151_350L{get;set;}
    public Decimal ExiTotanNumberOfProjectsWon351_700L{get;set;}
    public Decimal ExiTotanNumberOfProjectsWonGreaterThan700L{get;set;}
    
    public Decimal ExiTotanNumberOfProjects{get;set;}
    public Decimal ExiTotanNumberOfProjectsWon{get;set;}
    
    
    
    public Decimal NewTotanNumberOfProjects0_10L{get;set;}
    public Decimal NewTotanNumberOfProjects10_50L{get;set;}
    public Decimal NewTotanNumberOfProjects51_150L{get;set;}
    public Decimal NewTotanNumberOfProjects151_350L{get;set;}
    public Decimal NewTotanNumberOfProjects351_700L{get;set;}
    public Decimal NewTotanNumberOfProjectsGreaterThan700L{get;set;}
    
    public Decimal NewTotanNumberOfProjectsWon0_10L{get;set;}
    public Decimal NewTotanNumberOfProjectsWon10_50L{get;set;}
    public Decimal NewTotanNumberOfProjectsWon51_150L{get;set;}
    public Decimal NewTotanNumberOfProjectsWon151_350L{get;set;}
    public Decimal NewTotanNumberOfProjectsWon351_700L{get;set;}
    public Decimal NewTotanNumberOfProjectsWonGreaterThan700L{get;set;}
    
    public Decimal NewTotanNumberOfProjects{get;set;}
    public Decimal NewTotanNumberOfProjectsWon{get;set;}
    
    public set<ID> OpIdList = new set<ID>();
    public List<SelectOption> lstOptions {get; set;}
    
    public Fetchmbadata2() {
        lstOptions = new List<SelectOption>();
        
        lstOptions.add(new SelectOption('0',' - - - Select - - - '));
        lstOptions.add(new SelectOption('1','Current FY'));
        lstOptions.add(new SelectOption('2','Previous FY'));
        lstOptions.add(new SelectOption('3','Current FQ'));
        lstOptions.add(new SelectOption('4','Previous FQ'));
        lstOptions.add(new SelectOption('5','This Month'));
        lstOptions.add(new SelectOption('6','Last Month'));
        
        system.debug('@@@@'+ monthSelected);
        
        dateformat=false;
        
    
  
    
        Quote_submitted=0;
        Still_active=0;
        Oppurtunity_on_hold=0;
        Projects_shelved=0;
        Awarded_PO_by_customer=0;
        Order_won=0;
        Lost_on_Cost=0;
        Lost_on_Lead_time=0;
        Lost_on_strategic_reasons=0;
        Regret=0;
        Overall=0;
        Overall1=0;
        
        PerQuote_submitted=0;
        PerStill_active=0;
        PerOppurtunity_on_hold=0;
        PerProjects_shelved=0;
        PerAwarded_PO_by_customer=0;
        PerOrder_won=0;
        PerLost_on_Cost=0;
        PerLost_on_Lead_time=0;
        PerLost_on_strategic_reasons=0;
        PerRegret=0;
        
        OWafunne=0;
        OWafunnee=0;
        OWrqsub=0;
        OWacfqt=0;
        OWqtprep=0;
        ACafunne=0;
        ACafunnee=0;
        ACundneg=0;
        ACrqsub=0;
        ACacfqt=0;
        ACqtprep=0;
        SAafunne=0;
        SAundneg=0;
        SArqsub=0;
        SAacfqt=0;
        SAqtprep=0;
        QSafunne=0;
        QSundneg=0;
        QSrqsub=0;
        QSacfqt=0;
        QSqtprep=0;
        
        OrdersWon=0;
        OrderWon0_10=0;
        OrderWon10_50=0;
        OrderWon51_150=0;
        OrderWon151_350=0;
        OrderWon351_700=0;
        OrderWonGreaterThan700L=0;
        
        QuotesSubmitted=0;
        QuotesSubmitted0_10L=0;
        QuotesSubmitted10_50L=0;
        QuotesSubmitted51_150L=0;
        QuotesSubmitted151_350L=0;
        QuotesSubmitted351_700L=0;
        QuotesSubmittedGreaterThan700L=0;
        
        Totalper=0;
        per0_10=0;
        per10_50=0;
        per51_150=0;
        per151_350=0;
        per351_700=0;
        pergtr700=0;
        
        ExpTotalper=0;
        Expper0_10=0;
        Expper10_50=0;
        Expper51_150=0;
        Expper151_350=0;
        Expper351_700=0;
        Exppergtr700=0;
        
        DomTotalper=0;
        Domper0_10=0;
        Domper10_50=0;
        Domper51_150=0;
        Domper151_350=0;
        Domper351_700=0;
        Dompergtr700=0;
        
        ExiTotalper=0;
        Exiper0_10=0;
        Exiper10_50=0;
        Exiper51_150=0;
        Exiper151_350=0;
        Exiper351_700=0;
        Exipergtr700=0;
        
        NewTotalper=0;
        Newper0_10=0;
        Newper10_50=0;
        Newper51_150=0;
        Newper151_350=0;
        Newper351_700=0;
        Newpergtr700=0;
            
        ExpOrdersWon=0;
        ExpOrderWon0_10=0;
        ExpOrderWon10_50=0;
        ExpOrderWon51_150=0;
        ExpOrderWon151_350=0;
        ExpOrderWon351_700=0;
        ExpOrderWonGreaterThan700L=0;
        
        ExpQuotesSubmitted=0;
        ExpQuotesSubmitted0_10L=0;
        ExpQuotesSubmitted10_50L=0;
        ExpQuotesSubmitted51_150L=0;
        ExpQuotesSubmitted151_350L=0;
        ExpQuotesSubmitted351_700L=0;
        ExpQuotesSubmittedGreaterThan700L=0;
        
        
        DomOrdersWon=0;
        DomOrderWon0_10=0;
        DomOrderWon10_50=0;
        DomOrderWon51_150=0;
        DomOrderWon151_350=0;
        DomOrderWon351_700=0;
        DomOrderWonGreaterThan700L=0;
        
        DomQuotesSubmitted=0;
        DomQuotesSubmitted0_10L=0;
        DomQuotesSubmitted10_50L=0;
        DomQuotesSubmitted51_150L=0;
        DomQuotesSubmitted151_350L=0;
        DomQuotesSubmitted351_700L=0;
        DomQuotesSubmittedGreaterThan700L=0;
        
        
        ExiOrdersWon=0;
        ExiOrderWon0_10=0;
        ExiOrderWon10_50=0;
        ExiOrderWon51_150=0;
        ExiOrderWon151_350=0;
        ExiOrderWon351_700=0;
        ExiOrderWonGreaterThan700L=0;
        
        ExiQuotesSubmitted=0;
        ExiQuotesSubmitted0_10L=0;
        ExiQuotesSubmitted10_50L=0;
        ExiQuotesSubmitted51_150L=0;
        ExiQuotesSubmitted151_350L=0;
        ExiQuotesSubmitted351_700L=0;
        ExiQuotesSubmittedGreaterThan700L=0;
        
        
        NewOrdersWon=0;
        NewOrderWon0_10=0;
        NewOrderWon10_50=0;
        NewOrderWon51_150=0;
        NewOrderWon151_350=0;
        NewOrderWon351_700=0;
        NewOrderWonGreaterThan700L=0;
        
        NewQuotesSubmitted=0;
        NewQuotesSubmitted0_10L=0;
        NewQuotesSubmitted10_50L=0;
        NewQuotesSubmitted51_150L=0;
        NewQuotesSubmitted151_350L=0;
        NewQuotesSubmitted351_700L=0;
        NewQuotesSubmittedGreaterThan700L=0;
        
        oplisttemp=new List<opportunity>();
        
         
        TotanNumberOfProjects=0;
        TotanNumberOfProjects0_10L=0;
        TotanNumberOfProjects10_50L=0;
        TotanNumberOfProjects51_150L=0;
        TotanNumberOfProjects151_350L=0;
        TotanNumberOfProjects351_700L=0;
        TotanNumberOfProjectsGreaterThan700L=0;
        
        TotanNumberOfProjectsWon=0;
        TotanNumberOfProjectsWon0_10L=0;
        TotanNumberOfProjectsWon10_50L=0;
        TotanNumberOfProjectsWon51_150L=0;
        TotanNumberOfProjectsWon151_350L=0;
        TotanNumberOfProjectsWon351_700L=0;
        TotanNumberOfProjectsWonGreaterThan700L=0;
    
    
        ExpTotanNumberOfProjects=0;
        ExpTotanNumberOfProjects0_10L=0;
        ExpTotanNumberOfProjects10_50L=0;
        ExpTotanNumberOfProjects51_150L=0;
        ExpTotanNumberOfProjects151_350L=0;
        ExpTotanNumberOfProjects351_700L=0;
        ExpTotanNumberOfProjectsGreaterThan700L=0;
        
        ExpTotanNumberOfProjectsWon=0;
        ExpTotanNumberOfProjectsWon0_10L=0;
        ExpTotanNumberOfProjectsWon10_50L=0;
        ExpTotanNumberOfProjectsWon51_150L=0;
        ExpTotanNumberOfProjectsWon151_350L=0;
        ExpTotanNumberOfProjectsWon351_700L=0;
        ExpTotanNumberOfProjectsWonGreaterThan700L=0;
        
        
        DomTotanNumberOfProjects=0;
        DomTotanNumberOfProjects0_10L=0;
        DomTotanNumberOfProjects10_50L=0;
        DomTotanNumberOfProjects51_150L=0;
        DomTotanNumberOfProjects151_350L=0;
        DomTotanNumberOfProjects351_700L=0;
        DomTotanNumberOfProjectsGreaterThan700L=0;
        
        DomTotanNumberOfProjectsWon=0;
        DomTotanNumberOfProjectsWon0_10L=0;
        DomTotanNumberOfProjectsWon10_50L=0;
        DomTotanNumberOfProjectsWon51_150L=0;
        DomTotanNumberOfProjectsWon151_350L=0;
        DomTotanNumberOfProjectsWon351_700L=0;
        DomTotanNumberOfProjectsWonGreaterThan700L=0;
        
        ExiTotanNumberOfProjects=0;
        ExiTotanNumberOfProjects0_10L=0;
        ExiTotanNumberOfProjects10_50L=0;
        ExiTotanNumberOfProjects51_150L=0;
        ExiTotanNumberOfProjects151_350L=0;
        ExiTotanNumberOfProjects351_700L=0;
        ExiTotanNumberOfProjectsGreaterThan700L=0;
        
        ExiTotanNumberOfProjectsWon=0;
        ExiTotanNumberOfProjectsWon0_10L=0;
        ExiTotanNumberOfProjectsWon10_50L=0;
        ExiTotanNumberOfProjectsWon51_150L=0;
        ExiTotanNumberOfProjectsWon151_350L=0;
        ExiTotanNumberOfProjectsWon351_700L=0;
        ExiTotanNumberOfProjectsWonGreaterThan700L=0;
        
        
        NewTotanNumberOfProjects=0;
        NewTotanNumberOfProjects0_10L=0;
        NewTotanNumberOfProjects10_50L=0;
        NewTotanNumberOfProjects51_150L=0;
        NewTotanNumberOfProjects151_350L=0;
        NewTotanNumberOfProjects351_700L=0;
        NewTotanNumberOfProjectsGreaterThan700L=0;
        
        NewTotanNumberOfProjectsWon=0;
        NewTotanNumberOfProjectsWon0_10L=0;
        NewTotanNumberOfProjectsWon10_50L=0;
        NewTotanNumberOfProjectsWon51_150L=0;
        NewTotanNumberOfProjectsWon151_350L=0;
        NewTotanNumberOfProjectsWon351_700L=0;
        NewTotanNumberOfProjectsWonGreaterThan700L=0;
       
        /*-------------------------fatching Record type id for Account and opportunity-------------------------*/
        ID RtAccountMBA;
        ID RtIdAllocatedRecordType;
        ID RtIdAwaitFeedbackRecordType;
        ID RtIdInitialRecordtype;
        ID RtIdLayoutRecordType;
        ID RtIdMBA;
        ID RtIdMBAServicesAllocated;
        ID RtIdMBAServicesFinal;
        ID RtIdMBASparesFinal;
        ID RtIdPECSA;
        ID RtIdQuoteSubmittedRecordType;
        ID RtIdQuoteSubmittedServices;
        ID RtIdQuoteSubmittedSpares;
        ID RtIdRegretMBARecordType;
        ID RtIdSpareServicesRecordType;
        /*----------------------------------fatching account record type id------------------------------------------------*/
       List<RecordType> AccountRt = [select name,id from RecordType where Sobjecttype='Account'];
       for(RecordType ActRt: AccountRt)
       {
            if(ActRt.name=='MBA')
            {
                RtAccountMBA=ActRt.id;
                
            }
           
       }
        
        /*--------------------------------------------fatching opportunity reocrdtype id------------------------------------*/
        List<RecordType> Rt = [select name,id from RecordType where Sobjecttype='Opportunity'];  
        for(RecordType Rtype : Rt)
        {

            if(Rtype.name=='Allocated Record Type')
            {
                RtIdAllocatedRecordType = Rtype.id;
            }
            if(Rtype.name=='Await Feedback Record Type')
            {
                RtIdAwaitFeedbackRecordType = Rtype.id;
            }
            if(Rtype.name=='Initial Record type')
            {
                RtIdInitialRecordtype = Rtype.id;
            }
            if(Rtype.name=='Layout Record Type')
            {
                RtIdLayoutRecordType = Rtype.id;
            }
            if(Rtype.name=='MBA')
            {
                RtIdMBA = Rtype.id;
            }
            if(Rtype.name=='MBA Services Allocated')
            {
                RtIdMBAServicesAllocated = Rtype.id;
            }
            if(Rtype.name=='MBA Services Final')
            {
                RtIdMBAServicesFinal = Rtype.id;
            }
            if(Rtype.name=='MBA Spares Final')
            {
                RtIdMBASparesFinal = Rtype.id;
            }
            if(Rtype.name=='PECSA')
            {
                RtIdPECSA = Rtype.id;
            }
            if(Rtype.name=='Quote Submitted Record Type')
            {
                RtIdQuoteSubmittedRecordType = Rtype.id; 
            }
            if(Rtype.name=='Quote Submitted Services')
            {
                RtIdQuoteSubmittedServices = Rtype.id;
            }
            if(Rtype.name=='Quote Submitted Spares')
            {
                RtIdQuoteSubmittedSpares = Rtype.id;
            }
            if(Rtype.name=='Regret MBA Record Type')
            {
                RtIdRegretMBARecordType = Rtype.id;
            }
            if(Rtype.name=='Spares & Services Record Type')
            {
                RtIdSpareServicesRecordType = Rtype.id;
            }
        }
     List<Quote> QuoteList=new List <Quote> ();
    system.debug('*********************************'+monthSelected);   
    
      if(fromdate == null)
     {
       
            if(monthSelected=='1' ||Test.isRunningTest())
            {
                OpIdList = new set<ID>();
                QuoteList  = new List <Quote> ();
                system.debug('!!!!!!!!THIS_FISCAL_YEAR!!!!!!!');
                QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= THIS_FISCAL_YEAR];
            }
            
            if(monthSelected=='2'||Test.isRunningTest())
            {  
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!LAST_FISCAL_YEAR!!!!!!!');
                QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= LAST_FISCAL_YEAR];
                System.debug('*********************************************************quote*******************************************'+QuoteList);
            }
            
            if(monthSelected=='3' ||Test.isRunningTest())
            {  
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!THIS_FISCAL_QUARTER!!!!!!!');
                 QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= THIS_FISCAL_QUARTER];
            }
            
            if(monthSelected=='4')
            {
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!LAST_FISCAL_QUARTER!!!!!!!');
                QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= LAST_FISCAL_QUARTER ];
            }
            
            if(monthSelected=='5')
            {
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!THIS_MONTH!!!!!!!');
                QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= THIS_MONTH];
            }
            
            if(monthSelected=='6')
            {
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!LAST_MONTH!!!!!!!');
                 QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= LAST_MONTH];
            }
                 
     }
    else{
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!LAST_MONTH!!!!!!!');
                 QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c >= :fromdate AND Opportunity.First_Quote_Created_Date__c <= :todate];
            
    }
    
      
       
        for(Quote Q : QuoteList)
        {
            OpIdList.add(Q.OpportunityId); 
        }
        System.debug('*********************************************oppId*******************************************************'+OpIdList);
        List<opportunity> oplist =[select id,StageName,name,Converted_Amount__c ,Project_Type__c,Customer_Type__c,RecordTypeId,RecordType.Name,Account.RecordTypeId,Amount,Reason__c,Cost_band__c from opportunity where id in: OpIdList];
      
        
        
        for(Opportunity op : oplist)
         {
         if((op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
              op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
         
             system.debug('-----------------------For 1st Dashboard----------------');
             
            if(op.StageName=='Await Customer Feedback(Quote Submitted)' || op.StageName=='Revised Quote Submission'
                ||op.StageName=='Under Negotiation' || op.StageName=='Await Feedback (Under Negotiation)'||op.StageName=='Order Won'
                ||op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Opportunity On Hold' || op.StageName=='Opportunity Lost' || op.StageName=='Project Cancelled'
                ||op.StageName=='Project On Hold')
            {
                Quote_submitted=Quote_submitted+op.Amount;
                if(op.StageName=='Quote Preparation')
                {
                    QSqtprep=QSqtprep+op.Amount;
                }
                if(op.StageName=='Await Customer Feedback(Quote Submitted)')
                {
                    QSacfqt=QSacfqt+op.Amount;
                }
                if(op.StageName=='Revised Quote Submission')
                {
                    QSrqsub=QSrqsub+op.Amount;
                }
                if(op.StageName=='Under Negotiation')
                {
                    QSundneg=QSundneg+op.Amount;
                }
                if(op.StageName=='Await Feedback (Under Negotiation)')
                {
                    QSafunne=QSafunne+op.Amount;
                }
               
                
            }
            
            if(op.StageName=='Await Customer Feedback(Quote Submitted)' || op.StageName=='Revised Quote Submission'
                ||op.StageName=='Under Negotiation' || op.StageName=='Await Feedback (Under Negotiation)')
            {
                Still_active=Still_active+op.Amount;
                if(op.StageName=='Quote Preparation')
                {
                    SAqtprep=SAqtprep+op.Amount;
                }
                if(op.StageName=='Await Customer Feedback(Quote Submitted)')
                {
                    SAacfqt=SAacfqt+op.Amount;
                }
                if(op.StageName=='Revised Quote Submission')
                {
                    SArqsub=SArqsub+op.Amount;
                }
                if(op.StageName=='Under Negotiation')
                {
                    SAundneg=SAundneg+op.Amount;
                }
                if(op.StageName=='Await Feedback (Under Negotiation)')
                {
                    SAafunne=SAafunne+op.Amount;
                }
            }
            
            if(op.StageName=='Opportunity On Hold')
            {
                Oppurtunity_on_hold=Oppurtunity_on_hold+op.Amount;
            }
            if(op.Reason__c=='Project Shelved')
            {
                Projects_shelved=Projects_shelved+op.Amount;
            }
            if(op.Reason__c =='Lost on strategic reason'  
               ||  op.StageName=='Opportunity Lost' || op.StageName=='Project On Hold'|| op.StageName=='Project Cancelled')
            {
                Awarded_PO_by_customer=Awarded_PO_by_customer+op.Amount;
                if(op.StageName=='Order Won')
                {
                    ACqtprep=ACqtprep+op.Amount;
                }
                if(op.StageName=='Project Under Execution' )
                {
                    ACacfqt=ACacfqt+op.Amount;
                }
                if(op.StageName=='Project Closed')
                {
                    ACrqsub=ACrqsub+op.Amount;
                }
                if(op.StageName=='Opportunity Lost')
                {
                    ACundneg=ACundneg+op.Amount;
                }
                if(op.StageName=='Project On Hold')
                {
                    ACafunne=ACafunne+op.Amount;
                }
                if(op.StageName=='Project Cancelled')
                {
                    ACafunnee=ACafunnee+op.Amount;
                }
            }
            if(op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed'|| op.StageName=='Project On Hold'|| op.StageName=='Project Cancelled')
            {
                Order_won=Order_won+op.Amount;
                if(op.StageName=='Order Won')
                {
                    OWqtprep=OWqtprep+op.Amount;
                }
                if(op.StageName=='Project Under Execution' )
                {
                    OWacfqt=OWacfqt+op.Amount;
                }
                if(op.StageName=='Project Closed')
                {
                    OWrqsub=OWrqsub+op.Amount;
                }
                
                if(op.StageName=='Project On Hold')
                {
                    OWafunne=OWafunne+op.Amount;
                }
                if(op.StageName=='Project Cancelled')
                {
                    OWafunnee=OWafunnee+op.Amount;
                }
            }
            if(op.Reason__c=='Lost on cost' ||op.Reason__c=='High Price')
            {
              
                Lost_on_Cost=Lost_on_Cost+op.Amount;
                
            }
            if(op.Reason__c=='Lost on lead time')
            {
                Lost_on_Lead_time=Lost_on_Lead_time+op.Amount;
            }
            if(op.Reason__c=='Lost on strategic reason')
            {
                Lost_on_strategic_reasons=Lost_on_strategic_reasons+op.Amount;
            }
            if(op.Reason__c=='Regret')
            {
                Regret=Regret+op.Amount;
            }
         }
         }
         Regret=Regret/100000;
         Lost_on_strategic_reasons=Lost_on_strategic_reasons/100000;
         Lost_on_Lead_time=Lost_on_Lead_time/100000;
         Lost_on_Cost=Lost_on_Cost/100000;
         Order_won=Order_won/100000;
         Awarded_PO_by_customer=Awarded_PO_by_customer/100000;
         Projects_shelved=Projects_shelved/100000;
         Oppurtunity_on_hold=Oppurtunity_on_hold/100000;
         Still_active=Still_active/100000;
         Quote_submitted=Quote_submitted/100000;
         
       Overall=Awarded_PO_by_customer+Projects_shelved+Oppurtunity_on_hold+Still_active+Quote_submitted;
         Overall1=Regret+Lost_on_strategic_reasons+Lost_on_Lead_time+Lost_on_Cost+Order_won;
         
          if(Overall !=0 && Overall1 !=0){
        //PerQuote_submitted=(Quote_submitted/Overall)*100;
        PerStill_active=(Still_active/Overall)*100;
        PerOppurtunity_on_hold=(Oppurtunity_on_hold/Overall)*100;
        PerProjects_shelved=(Projects_shelved/Overall)*100;
        PerAwarded_PO_by_customer=(Awarded_PO_by_customer/Overall)*100;
        PerOrder_won=(Order_won/Overall1)*100;
        PerLost_on_Cost=(Lost_on_Cost/Overall1)*100;
        PerLost_on_Lead_time=(Lost_on_Lead_time/Overall1)*100;
        PerLost_on_strategic_reasons=(Lost_on_strategic_reasons/Overall1)*100;
        PerRegret=(Regret/Overall1)*100;
         }
         
         system.debug('$$$$$$$$Overall$$$$$$$$$$$'+Overall);
         system.debug('$$$$$$$$$Overall1$$$$$$$$$$'+Overall1);
         system.debug('$$$$$$$$Quote_submitted$$$$$$$$$$$'+Quote_submitted);
         system.debug('$$$$$$$$$Still_active$$$$$$$$$$'+Still_active);
         system.debug('$$$$$$$$$Oppurtunity_on_hold$$$$$$$$$$'+Oppurtunity_on_hold);
         system.debug('$$$$$$$$Projects_shelved$$$$$$$$$$$'+Projects_shelved);
         system.debug('$$$$$$$$$Awarded_PO_by_customer$$$$$$$$$$'+Awarded_PO_by_customer);
         system.debug('$$$$$$$$$Order_won$$$$$$$$$$'+Order_won);
         system.debug('$$$$$$$$Lost_on_Cost$$$$$$$$$$$'+Lost_on_Cost);
         system.debug('$$$$$$$$Lost_on_Lead_time$$$$$$$$$$$'+Lost_on_Lead_time);
         system.debug('$$$$$$$$$Lost_on_strategic_reasons$$$$$$$$$$'+Lost_on_strategic_reasons);
         system.debug('$$$$$$$$$Regret$$$$$$$$$$'+Regret);
       data= new List<Decimal>();
        
      
        
        data.add(Regret);
        data.add(Lost_on_strategic_reasons);
        data.add(Lost_on_Lead_time);
        data.add(Lost_on_Cost);
        data.add(Order_won);
        data.add(Awarded_PO_by_customer);
        data.add(Projects_shelved);
        data.add(Oppurtunity_on_hold);
        data.add(Still_active);
        data.add(Quote_submitted);
        
    
         
        for(Opportunity op : oplist)
         {
            if((op.Account.RecordTypeId==RtAccountMBA) &&(op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal &&
            op.RecordTypeId != RtIdMBASparesFinal && op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {            
                if(op.StageName=='Await Customer Feedback(Quote Submitted)' || op.StageName=='Revised Quote Submission'
                ||op.StageName=='Under Negotiation' || op.StageName=='Await Feedback (Under Negotiation)'||op.StageName=='Order Won'
                ||op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Opportunity On Hold' || op.StageName=='Opportunity Lost' || op.StageName=='Project Cancelled'
                ||op.StageName=='Project On Hold')
                {

                    /*---------------------------calculating QuotesSubmitted(Proposals Submitted - Win loss)---------------------------------------*/


                    system.debug('###################### In side Proposals Submitted - Win loss for all ################################');
                    TotanNumberOfProjects=TotanNumberOfProjects+1;
                    if(op.Amount!= null)
                    {
                    QuotesSubmitted=QuotesSubmitted+op.Amount;

                    }
                    if(op.Cost_band__c=='0-10L')
                    {   
                    TotanNumberOfProjects0_10L=TotanNumberOfProjects0_10L+1;
                    if(op.amount != null)
                    {
                    QuotesSubmitted0_10L = QuotesSubmitted0_10L + op.Amount;

                    }     
                    }         
                    if(op.Cost_band__c=='10-50L' || Test.isRunningTest())
                    {
                    TotanNumberOfProjects10_50L=TotanNumberOfProjects10_50L+1;
                    if(op.Amount != null)
                    {
                    QuotesSubmitted10_50L = QuotesSubmitted10_50L + op.Amount;

                    }
                    }
                    if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                    {
                    TotanNumberOfProjects51_150L=TotanNumberOfProjects51_150L+1;
                    if(op.Amount != Null)
                    {
                    QuotesSubmitted51_150L = QuotesSubmitted51_150L + op.Amount;

                    }
                    }
                    if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                    {
                    TotanNumberOfProjects151_350L=TotanNumberOfProjects51_150L+1;
                    if(op.Amount != Null)
                    {
                    QuotesSubmitted151_350L = QuotesSubmitted151_350L + op.Amount;

                    }
                    }
                    if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                    {
                    TotanNumberOfProjects351_700L=TotanNumberOfProjects351_700L+1;
                    if(op.Amount != Null)
                    {
                    QuotesSubmitted351_700L = QuotesSubmitted351_700L + op.Amount;

                    }
                    }
                    if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                    {
                    TotanNumberOfProjectsGreaterThan700L=TotanNumberOfProjectsGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                    QuotesSubmittedGreaterThan700L = QuotesSubmittedGreaterThan700L + op.Amount;

                    }    
                    }
                    
                    system.debug('*************************Out export Quote Submitted');



                    // for Export customer
                    if((op.Account.RecordTypeId==RtAccountMBA)&&(op.Project_Type__c =='Export'))
                    {
                        system.debug('###################### In side Proposals Submitted - Win loss for Export ################################');
                        ExpTotanNumberOfProjects=ExpTotanNumberOfProjects+1;
                        if(op.Amount!= null)
                        {
                        ExpQuotesSubmitted=ExpQuotesSubmitted+op.Amount;

                        }
                        if(op.Cost_band__c=='0-10L')
                        {   
                        ExpTotanNumberOfProjects0_10L=ExpTotanNumberOfProjects0_10L+1;
                        if(op.amount != null)
                        {
                        ExpQuotesSubmitted0_10L = ExpQuotesSubmitted0_10L + op.Amount;

                        }     
                        }         
                        if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                        {
                        ExpTotanNumberOfProjects10_50L=ExpTotanNumberOfProjects10_50L+1;
                        if(op.Amount != null)
                        {
                        ExpQuotesSubmitted10_50L = ExpQuotesSubmitted10_50L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                        {
                        ExpTotanNumberOfProjects51_150L=ExpTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        ExpQuotesSubmitted51_150L = ExpQuotesSubmitted51_150L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                        {
                        ExpTotanNumberOfProjects151_350L=ExpTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        ExpQuotesSubmitted151_350L = ExpQuotesSubmitted151_350L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                        {
                        ExpTotanNumberOfProjects351_700L=ExpTotanNumberOfProjects351_700L+1;
                        if(op.Amount != Null)
                        {
                        ExpQuotesSubmitted351_700L = ExpQuotesSubmitted351_700L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                        {
                        ExpTotanNumberOfProjectsGreaterThan700L=ExpTotanNumberOfProjectsGreaterThan700L+1;
                        if(op.Amount != null)
                        {
                        ExpQuotesSubmittedGreaterThan700L = ExpQuotesSubmittedGreaterThan700L + op.Amount;

                        }    
                        }
                    }



                    // for Domestic customer
                    if((op.Account.RecordTypeId==RtAccountMBA)&&(op.Project_Type__c =='Domestic'))
                    {
                        system.debug('###################### In side Proposals Submitted - Win loss for Domestic ################################');
                        DomTotanNumberOfProjects=DomTotanNumberOfProjects+1;
                        if(op.Amount!= null)
                        {
                        DomQuotesSubmitted=DomQuotesSubmitted+op.Amount;

                        }
                        if(op.Cost_band__c=='0-10L')
                        {   
                        DomTotanNumberOfProjects0_10L=DomTotanNumberOfProjects0_10L+1;
                        if(op.amount != null)
                        {
                        DomQuotesSubmitted0_10L = DomQuotesSubmitted0_10L + op.Amount;

                        }     
                        }         
                        if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                        {
                        DomTotanNumberOfProjects10_50L=DomTotanNumberOfProjects10_50L+1;
                        if(op.Amount != null)
                        {
                        DomQuotesSubmitted10_50L = DomQuotesSubmitted10_50L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                        {
                        DomTotanNumberOfProjects51_150L=DomTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        DomQuotesSubmitted51_150L = DomQuotesSubmitted51_150L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                        {
                        DomTotanNumberOfProjects151_350L=DomTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        DomQuotesSubmitted151_350L = DomQuotesSubmitted151_350L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                        {
                        DomTotanNumberOfProjects351_700L=DomTotanNumberOfProjects351_700L+1;
                        if(op.Amount != Null)
                        {
                        DomQuotesSubmitted351_700L = DomQuotesSubmitted351_700L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                        {
                        DomTotanNumberOfProjectsGreaterThan700L=DomTotanNumberOfProjectsGreaterThan700L+1;
                        if(op.Amount != null)
                        {
                        DomQuotesSubmittedGreaterThan700L = DomQuotesSubmittedGreaterThan700L + op.Amount;

                        }    
                        }
                    }


                    // for Existing Customer

                    if((op.Account.RecordTypeId==RtAccountMBA) && (op.Customer_Type__c=='Existing Customer') )
                    {
                        system.debug('###################### In side Proposals Submitted - Win loss for Existing ################################');
                        ExiTotanNumberOfProjects=ExiTotanNumberOfProjects+1;
                        if(op.Amount!= null)
                        {
                        ExiQuotesSubmitted=ExiQuotesSubmitted+op.Amount;

                        }
                        if(op.Cost_band__c=='0-10L')
                        {   
                        ExiTotanNumberOfProjects0_10L=ExiTotanNumberOfProjects0_10L+1;
                        if(op.amount != null)
                        {
                        ExiQuotesSubmitted0_10L = ExiQuotesSubmitted0_10L + op.Amount;

                        }     
                        }         
                        if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                        {
                        ExiTotanNumberOfProjects10_50L=ExiTotanNumberOfProjects10_50L+1;
                        if(op.Amount != null)
                        {
                        ExiQuotesSubmitted10_50L = ExiQuotesSubmitted10_50L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                        {
                        ExiTotanNumberOfProjects51_150L=ExiTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        ExiQuotesSubmitted51_150L = ExiQuotesSubmitted51_150L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                        {
                        ExiTotanNumberOfProjects151_350L=ExiTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        ExiQuotesSubmitted151_350L = ExiQuotesSubmitted151_350L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                        {
                        ExiTotanNumberOfProjects351_700L=ExiTotanNumberOfProjects351_700L+1;
                        if(op.Amount != Null)
                        {
                        ExiQuotesSubmitted351_700L = ExiQuotesSubmitted351_700L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                        {
                        ExiTotanNumberOfProjectsGreaterThan700L=ExiTotanNumberOfProjectsGreaterThan700L+1;
                        if(op.Amount != null)
                        {
                        ExiQuotesSubmittedGreaterThan700L = ExiQuotesSubmittedGreaterThan700L + op.Amount;

                        }    
                        }
                    }

                    // for New Customers

                    if((op.Account.RecordTypeId==RtAccountMBA) && (op.Customer_Type__c=='New') )
                    {
                        system.debug('###################### In side Proposals Submitted - Win loss for New ################################');
                        NewTotanNumberOfProjects=NewTotanNumberOfProjects+1;
                        if(op.Amount!= null)
                        {
                        NewQuotesSubmitted=NewQuotesSubmitted+op.Amount;

                        }
                        if(op.Cost_band__c=='0-10L')
                        {   
                        NewTotanNumberOfProjects0_10L=NewTotanNumberOfProjects0_10L+1;
                        if(op.amount != null)
                        {
                        NewQuotesSubmitted0_10L = NewQuotesSubmitted0_10L + op.Amount;

                        }     
                        }         
                        if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                        {
                        NewTotanNumberOfProjects10_50L=NewTotanNumberOfProjects10_50L+1;
                        if(op.Amount != null)
                        {
                        NewQuotesSubmitted10_50L = NewQuotesSubmitted10_50L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                        {
                        NewTotanNumberOfProjects51_150L=NewTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        NewQuotesSubmitted51_150L = NewQuotesSubmitted51_150L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                        {
                        NewTotanNumberOfProjects151_350L=NewTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        NewQuotesSubmitted151_350L = NewQuotesSubmitted151_350L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                        {
                        NewTotanNumberOfProjects351_700L=NewTotanNumberOfProjects351_700L+1;
                        if(op.Amount != Null)
                        {
                        NewQuotesSubmitted351_700L = NewQuotesSubmitted351_700L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                        {
                        NewTotanNumberOfProjectsGreaterThan700L=NewTotanNumberOfProjectsGreaterThan700L+1;
                        if(op.Amount != null)
                        {
                        NewQuotesSubmittedGreaterThan700L = NewQuotesSubmittedGreaterThan700L + op.Amount;

                        }    
                        }
                    }
                }
            }
        }
         QuotesSubmitted=QuotesSubmitted/100000;
         QuotesSubmitted0_10L=QuotesSubmitted0_10L/100000;
         QuotesSubmitted10_50L=QuotesSubmitted10_50L/100000;
         QuotesSubmitted51_150L=QuotesSubmitted51_150L/100000;
         QuotesSubmitted151_350L=QuotesSubmitted151_350L/100000;
         QuotesSubmitted351_700L=QuotesSubmitted351_700L/100000;
         QuotesSubmittedGreaterThan700L=QuotesSubmittedGreaterThan700L/100000;
         
         ExpQuotesSubmitted=ExpQuotesSubmitted/100000;
         ExpQuotesSubmitted0_10L=ExpQuotesSubmitted0_10L/100000;
         ExpQuotesSubmitted10_50L=ExpQuotesSubmitted10_50L/100000;
         ExpQuotesSubmitted51_150L=ExpQuotesSubmitted51_150L/100000;
         ExpQuotesSubmitted151_350L=ExpQuotesSubmitted151_350L/100000;
         ExpQuotesSubmitted351_700L=ExpQuotesSubmitted351_700L/100000;
         ExpQuotesSubmittedGreaterThan700L=ExpQuotesSubmittedGreaterThan700L/100000;
         
         DomQuotesSubmitted=DomQuotesSubmitted/100000;
         DomQuotesSubmitted0_10L=DomQuotesSubmitted0_10L/100000;
         DomQuotesSubmitted10_50L=DomQuotesSubmitted10_50L/100000;
         DomQuotesSubmitted51_150L=DomQuotesSubmitted51_150L/100000;
         DomQuotesSubmitted151_350L=DomQuotesSubmitted151_350L/100000;
         DomQuotesSubmitted351_700L=DomQuotesSubmitted351_700L/100000;
         DomQuotesSubmittedGreaterThan700L=DomQuotesSubmittedGreaterThan700L/100000;

         ExiQuotesSubmitted=ExiQuotesSubmitted/100000;
         ExiQuotesSubmitted0_10L=ExiQuotesSubmitted0_10L/100000;
         ExiQuotesSubmitted10_50L=ExiQuotesSubmitted10_50L/100000;
         ExiQuotesSubmitted51_150L=ExiQuotesSubmitted51_150L/100000;
         ExiQuotesSubmitted151_350L=ExiQuotesSubmitted151_350L/100000;
         ExiQuotesSubmitted351_700L=ExiQuotesSubmitted351_700L/100000;
         ExiQuotesSubmittedGreaterThan700L=ExiQuotesSubmittedGreaterThan700L/100000;
         
      
         
         NewQuotesSubmitted=NewQuotesSubmitted/100000;
         NewQuotesSubmitted0_10L=NewQuotesSubmitted0_10L/100000;
         NewQuotesSubmitted10_50L=NewQuotesSubmitted10_50L/100000;
         NewQuotesSubmitted51_150L=NewQuotesSubmitted51_150L/100000;
         NewQuotesSubmitted151_350L=NewQuotesSubmitted151_350L/100000;
         NewQuotesSubmitted351_700L=NewQuotesSubmitted351_700L/100000;
         NewQuotesSubmittedGreaterThan700L=NewQuotesSubmittedGreaterThan700L/100000;
       
         
         Decimal rounded = Math.round(QuotesSubmitted);
         Decimal rounded1 = Math.round(QuotesSubmitted0_10L);
         Decimal rounded2 = Math.round(QuotesSubmitted10_50L);
         Decimal rounded3 = Math.round(QuotesSubmitted51_150L);
         Decimal rounded4 = Math.round(QuotesSubmitted151_350L);
         Decimal rounded5 = Math.round(QuotesSubmitted351_700L);
         Decimal rounded6 = Math.round(QuotesSubmittedGreaterThan700L);
         
        
         /*--------------------------------------------------Calculating Orders Won------------------------------------------------------------*/
         List<opportunity> oplistForOrdersWon =[select id,name,StageName,Project_Type__c,Customer_Type__c,Converted_Amount__c ,RecordTypeId,RecordType.Name,Account.RecordTypeId,Amount, Cost_band__c from opportunity where (id in : OpIdList) ]; 
         
         for(Opportunity op : oplistForOrdersWon )
         {
            if((op.Account.RecordTypeId==RtAccountMBA) && 
            (op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Project Cancelled'|| op.StageName=='Project On Hold') && 
             
             (op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
              op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
             system.debug('###################### In side Orders Won for all ################################');
                oplisttemp.add(op);
                TotanNumberOfProjectsWon=TotanNumberOfProjectsWon+1;
                if(op.Cost_band__c=='0-10L')
                {   
                    TotanNumberOfProjectsWon0_10L=TotanNumberOfProjectsWon0_10L+1;
                    if(op.amount != null)
                    {
                        OrderWon0_10 = OrderWon0_10 + op.Amount;
                    }     
                }         
                if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                {
                    TotanNumberOfProjectsWon10_50L=TotanNumberOfProjectsWon10_50L+1;
                    if(op.Amount != null)
                    {
                        OrderWon10_50 = OrderWon10_50 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                {
                    TotanNumberOfProjectsWon51_150L=TotanNumberOfProjectsWon51_150L+1;
                    if(op.Amount != Null)
                    {
                        OrderWon51_150 = OrderWon51_150 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                {
                    TotanNumberOfProjectsWon151_350L=TotanNumberOfProjectsWon151_350L+1;
                    if(op.Amount != Null)
                    {
                        OrderWon151_350 = OrderWon151_350 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                {
                    TotanNumberOfProjectsWon351_700L=TotanNumberOfProjectsWon351_700L+1;
                    if(op.Amount != Null)
                    {
                        OrderWon351_700 = OrderWon351_700 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                {
                    TotanNumberOfProjectsWonGreaterThan700L=TotanNumberOfProjectsWonGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                        OrderWonGreaterThan700L = OrderWonGreaterThan700L + op.Amount;
                    }    
                }
                if(op.Amount != null)
                {
                    OrdersWon = OrdersWon + op.Amount;
                }  
            }
            system.debug('*************************out export order won');
       
       
       // ----------------------------------------------for Export customer--------------------------------------------------------
            if((op.Account.RecordTypeId==RtAccountMBA)&&(op.Project_Type__c == 'Export')&&
            (op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Project Cancelled'|| op.StageName=='Project On Hold') && 
             
                    (op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
                    op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
            
               system.debug('###################### In side Orders Won for Export ################################');
                oplisttemp.add(op);
                ExpTotanNumberOfProjectsWon=ExpTotanNumberOfProjectsWon+1;
                if(op.Cost_band__c=='0-10L')
                {   
                    ExpTotanNumberOfProjectsWon0_10L=ExpTotanNumberOfProjectsWon0_10L+1;
                    if(op.amount != null)
                    {
                        ExpOrderWon0_10 = ExpOrderWon0_10 + op.Amount;
                    }     
                }         
                if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                {
                    ExpTotanNumberOfProjectsWon10_50L=ExpTotanNumberOfProjectsWon10_50L+1;
                    if(op.Amount != null)
                    {
                        ExpOrderWon10_50 = ExpOrderWon10_50 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                {
                    ExpTotanNumberOfProjectsWon51_150L=ExpTotanNumberOfProjectsWon51_150L+1;
                    if(op.Amount != Null)
                    {
                        ExpOrderWon51_150 = ExpOrderWon51_150 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                {
                    ExpTotanNumberOfProjectsWon151_350L=ExpTotanNumberOfProjectsWon151_350L+1;
                    if(op.Amount != Null)
                    {
                        ExpOrderWon151_350 = ExpOrderWon151_350 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                {
                    ExpTotanNumberOfProjectsWon351_700L=ExpTotanNumberOfProjectsWon351_700L+1;
                    if(op.Amount != Null)
                    {
                        ExpOrderWon351_700 = ExpOrderWon351_700 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                {
                    ExpTotanNumberOfProjectsWonGreaterThan700L=ExpTotanNumberOfProjectsWonGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                        ExpOrderWonGreaterThan700L = ExpOrderWonGreaterThan700L + op.Amount;
                    }    
                }
                if(op.Amount != null)
                {
                    ExpOrdersWon = ExpOrdersWon + op.Amount;
                }  
            }   
    
    
    // -------------------------------------for Domestic customer-------------------------------------------------------------
            if((op.Account.RecordTypeId==RtAccountMBA)&&(op.Project_Type__c == 'Domestic')&&
            (op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Project Cancelled'|| op.StageName=='Project On Hold') && 
             
                    (op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
                    op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
            
                system.debug('###################### In side Orders Won for Domestic ################################');
                oplisttemp.add(op);
                DomTotanNumberOfProjectsWon=DomTotanNumberOfProjectsWon+1;
                if(op.Cost_band__c=='0-10L')
                {   
                    DomTotanNumberOfProjectsWon0_10L=DomTotanNumberOfProjectsWon0_10L+1;
                    if(op.amount != null)
                    {
                        DomOrderWon0_10 = DomOrderWon0_10 + op.Amount;
                    }     
                }         
                if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                {
                    DomTotanNumberOfProjectsWon10_50L=DomTotanNumberOfProjectsWon10_50L+1;
                    if(op.Amount != null)
                    {
                        DomOrderWon10_50 = DomOrderWon10_50 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                {
                    DomTotanNumberOfProjectsWon51_150L=DomTotanNumberOfProjectsWon51_150L+1;
                    if(op.Amount != Null)
                    {
                        DomOrderWon51_150 = DomOrderWon51_150 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                {
                    DomTotanNumberOfProjectsWon151_350L=DomTotanNumberOfProjectsWon151_350L+1;
                    if(op.Amount != Null)
                    {
                        DomOrderWon151_350 = DomOrderWon151_350 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                {
                    DomTotanNumberOfProjectsWon351_700L=DomTotanNumberOfProjectsWon351_700L+1;
                    if(op.Amount != Null)
                    {
                        DomOrderWon351_700 = DomOrderWon351_700 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                {
                    DomTotanNumberOfProjectsWonGreaterThan700L=DomTotanNumberOfProjectsWonGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                        DomOrderWonGreaterThan700L = DomOrderWonGreaterThan700L + op.Amount;
                    }    
                }
                if(op.Amount != null)
                {
                    DomOrdersWon = DomOrdersWon + op.Amount;
                }  
            }   
            
    //------------------------------------------ for Existing customers---------------------------------------------------

                if((op.Account.RecordTypeId==RtAccountMBA) && (op.Customer_Type__c=='Existing Customer') &&
            (op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Project Cancelled'|| op.StageName=='Project On Hold') && 
             
             (op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
              op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
            system.debug('###################### In side Orders Won for Existing ################################');
                oplisttemp.add(op);
                ExiTotanNumberOfProjectsWon=ExiTotanNumberOfProjectsWon+1;
                if(op.Cost_band__c=='0-10L')
                {   
                    ExiTotanNumberOfProjectsWon0_10L=ExiTotanNumberOfProjectsWon0_10L+1;
                    if(op.amount != null)
                    {
                        ExiOrderWon0_10 = ExiOrderWon0_10 + op.Amount;
                    }     
                }         
                if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                {
                    ExiTotanNumberOfProjectsWon10_50L=ExiTotanNumberOfProjectsWon10_50L+1;
                    if(op.Amount != null)
                    {
                        ExiOrderWon10_50 = ExiOrderWon10_50 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                {
                    ExiTotanNumberOfProjectsWon51_150L=ExiTotanNumberOfProjectsWon51_150L+1;
                    if(op.Amount != Null)
                    {
                        ExiOrderWon51_150 = ExiOrderWon51_150 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                {
                    ExiTotanNumberOfProjectsWon151_350L=ExiTotanNumberOfProjectsWon151_350L+1;
                    if(op.Amount != Null)
                    {
                        ExiOrderWon151_350 = ExiOrderWon151_350 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                {
                    ExiTotanNumberOfProjectsWon351_700L=ExiTotanNumberOfProjectsWon351_700L+1;
                    if(op.Amount != Null)
                    {
                        ExiOrderWon351_700 = ExiOrderWon351_700 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                {
                    ExiTotanNumberOfProjectsWonGreaterThan700L=ExiTotanNumberOfProjectsWonGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                        ExiOrderWonGreaterThan700L = ExiOrderWonGreaterThan700L + op.Amount;
                    }    
                }
                if(op.Amount != null)
                {
                    ExiOrdersWon = ExiOrdersWon + op.Amount;
                }  
            }
            
            
    //------------------------------------------------------------- for New Customer------------------------------------------------

                if((op.Account.RecordTypeId==RtAccountMBA) && (op.Customer_Type__c=='New') &&
            (op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Project Cancelled'|| op.StageName=='Project On Hold') && 
             
             (op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
              op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
            system.debug('###################### In side Orders Won for New ################################');
                oplisttemp.add(op);
                NewTotanNumberOfProjectsWon=NewTotanNumberOfProjectsWon+1;
                if(op.Cost_band__c=='0-10L')
                {   
                    NewTotanNumberOfProjectsWon0_10L=NewTotanNumberOfProjectsWon0_10L+1;
                    if(op.amount != null)
                    {
                        NewOrderWon0_10 = NewOrderWon0_10 + op.Amount;
                    }     
                }         
                if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                {
                    NewTotanNumberOfProjectsWon10_50L=NewTotanNumberOfProjectsWon10_50L+1;
                    if(op.Amount != null)
                    {
                        NewOrderWon10_50 = NewOrderWon10_50 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                {
                    NewTotanNumberOfProjectsWon51_150L=NewTotanNumberOfProjectsWon51_150L+1;
                    if(op.Amount != Null)
                    {
                        NewOrderWon51_150 = NewOrderWon51_150 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                {
                    NewTotanNumberOfProjectsWon151_350L=NewTotanNumberOfProjectsWon151_350L+1;
                    if(op.Amount != Null)
                    {
                        NewOrderWon151_350 = NewOrderWon151_350 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                {
                    NewTotanNumberOfProjectsWon351_700L=NewTotanNumberOfProjectsWon351_700L+1;
                    if(op.Amount != Null)
                    {
                        NewOrderWon351_700 = NewOrderWon351_700 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                {
                    NewTotanNumberOfProjectsWonGreaterThan700L=NewTotanNumberOfProjectsWonGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                        NewOrderWonGreaterThan700L = NewOrderWonGreaterThan700L + op.Amount;
                    }    
                }
                if(op.Amount != null)
                {
                    NewOrdersWon = NewOrdersWon + op.Amount;
                }  
            }
         }
        
        OrdersWon=OrdersWon/100000;
        OrderWon0_10=OrderWon0_10/100000;
        OrderWon10_50=OrderWon10_50/100000;
        OrderWon51_150=OrderWon51_150/100000;
        OrderWon151_350=OrderWon151_350/100000;
        OrderWon351_700=OrderWon351_700/100000;
        OrderWonGreaterThan700L=OrderWonGreaterThan700L/100000;
        
        ExpOrdersWon=ExpOrdersWon/100000;
        ExpOrderWon0_10=ExpOrderWon0_10/100000;
        ExpOrderWon10_50=ExpOrderWon10_50/100000;
        ExpOrderWon51_150=ExpOrderWon51_150/100000;
        ExpOrderWon151_350=ExpOrderWon151_350/100000;
        ExpOrderWon351_700=ExpOrderWon351_700/100000;
        ExpOrderWonGreaterThan700L=ExpOrderWonGreaterThan700L/100000;
        
        DomOrdersWon=DomOrdersWon/100000;
        DomOrderWon0_10=DomOrderWon0_10/100000;
        DomOrderWon10_50=DomOrderWon10_50/100000;
        DomOrderWon51_150=DomOrderWon51_150/100000;
        DomOrderWon151_350=DomOrderWon151_350/100000;
        DomOrderWon351_700=DomOrderWon351_700/100000;
        DomOrderWonGreaterThan700L=DomOrderWonGreaterThan700L/100000;
        
        ExiOrdersWon=ExiOrdersWon/100000;
        ExiOrderWon0_10=ExiOrderWon0_10/100000;
        ExiOrderWon10_50=ExiOrderWon10_50/100000;
        ExiOrderWon51_150=ExiOrderWon51_150/100000;
        ExiOrderWon151_350=ExiOrderWon151_350/100000;
        ExiOrderWon351_700=ExiOrderWon351_700/100000;
        ExiOrderWonGreaterThan700L=ExiOrderWonGreaterThan700L/100000;
        
        
        NewOrdersWon=NewOrdersWon/100000;
        NewOrderWon0_10=NewOrderWon0_10/100000;
        NewOrderWon10_50=NewOrderWon10_50/100000;
        NewOrderWon51_150=NewOrderWon51_150/100000;
        NewOrderWon151_350=NewOrderWon151_350/100000;
        NewOrderWon351_700=NewOrderWon351_700/100000;
        NewOrderWonGreaterThan700L=NewOrderWonGreaterThan700L/100000;
        
        Decimal rounded7 = Math.round(OrdersWon);
        Decimal rounded8 = Math.round(OrderWon0_10);
        Decimal rounded9 = Math.round(OrderWon10_50);
        Decimal rounded10 = Math.round(OrderWon51_150);
        Decimal rounded11 = Math.round(OrderWon151_350);
        Decimal rounded12 = Math.round(OrderWon351_700);
        Decimal rounded13 = Math.round(OrderWonGreaterThan700L);
        
       
    //---------------------------------------------------------- for calculating percentage of submitted  Vs Won----------------------------   
        if(QuotesSubmitted>0){
        
           Totalper=(OrdersWon*100)/QuotesSubmitted;
        }
        if(QuotesSubmitted0_10L>0){
        
             per0_10=(OrderWon0_10*100)/QuotesSubmitted0_10L;
        }
         if(QuotesSubmitted10_50L>0){
        
             per10_50=(OrderWon10_50*100)/QuotesSubmitted10_50L;
        }
        if(QuotesSubmitted51_150L>0){
        
             per51_150=(OrderWon51_150*100)/QuotesSubmitted51_150L;
        }
        if(QuotesSubmitted151_350L>0){
        
             per151_350=(OrderWon151_350*100)/QuotesSubmitted151_350L;
        }
        if(QuotesSubmitted351_700L>0){
        
            per351_700=(OrderWon351_700*100)/QuotesSubmitted351_700L;
        }
        if(QuotesSubmittedGreaterThan700L>0){
        
             pergtr700=(OrderWonGreaterThan700L*100)/QuotesSubmittedGreaterThan700L;
        }
      //---------------------------------------------------------percentage of no of project submitted Vs Won---------------------------
      
        if(TotanNumberOfProjects>0){
        
              NTotalper=(TotanNumberOfProjectsWon*100)/TotanNumberOfProjects;
        }
        if(TotanNumberOfProjects0_10L>0){
        
              Nper0_10=(TotanNumberOfProjectsWon0_10L*100)/TotanNumberOfProjects0_10L;
        }
        if(TotanNumberOfProjects10_50L>0){
        
              Nper10_50=(TotanNumberOfProjectsWon10_50L*100)/TotanNumberOfProjects10_50L;
        }
        if(TotanNumberOfProjects51_150L>0){
        
              Nper51_150=(TotanNumberOfProjectsWon51_150L*100)/TotanNumberOfProjects51_150L;
        }
        if(TotanNumberOfProjects151_350L>0){
        
              Nper151_350=(TotanNumberOfProjectsWon151_350L*100)/TotanNumberOfProjects151_350L;
        }
        if(TotanNumberOfProjects351_700L>0){
        
              Nper351_700=(TotanNumberOfProjectsWon351_700L*100)/TotanNumberOfProjects351_700L;
        }
        if(TotanNumberOfProjectsGreaterThan700L>0){
        
              Npergtr700=(TotanNumberOfProjectsWonGreaterThan700L*100)/TotanNumberOfProjectsGreaterThan700L;
        }
      
      
       //---------------------------------------------------------- for calculating percentage of submitted  Vs Won for Export----------------------------   
        if(ExpQuotesSubmitted>0){
        
           ExpTotalper=(ExpOrdersWon*100)/ExpQuotesSubmitted;
        }
        if(ExpQuotesSubmitted0_10L>0){
        
             Expper0_10=(ExpOrderWon0_10*100)/ExpQuotesSubmitted0_10L;
        }
         if(ExpQuotesSubmitted10_50L>0){
        
             Expper10_50=(ExpOrderWon10_50*100)/ExpQuotesSubmitted10_50L;
        }
        if(ExpQuotesSubmitted51_150L>0){
        
             Expper51_150=(ExpOrderWon51_150*100)/ExpQuotesSubmitted51_150L;
        }
        if(ExpQuotesSubmitted151_350L>0){
        
             Expper151_350=(ExpOrderWon151_350*100)/ExpQuotesSubmitted151_350L;
        }
        if(ExpQuotesSubmitted351_700L>0){
        
            Expper351_700=(ExpOrderWon351_700*100)/ExpQuotesSubmitted351_700L;
        }
        if(ExpQuotesSubmittedGreaterThan700L>0){
        
             Exppergtr700=(ExpOrderWonGreaterThan700L*100)/ExpQuotesSubmittedGreaterThan700L;
        }
      //---------------------------------------------------------percentage of no of project submitted Vs Won for Export---------------------------
      
        if(ExpTotanNumberOfProjects>0){
        
              ExpNTotalper=(ExpTotanNumberOfProjectsWon*100)/ExpTotanNumberOfProjects;
        }
        if(ExpTotanNumberOfProjects0_10L>0){
        
              ExpNper0_10=(ExpTotanNumberOfProjectsWon0_10L*100)/ExpTotanNumberOfProjects0_10L;
        }
        if(ExpTotanNumberOfProjects10_50L>0){
        
              ExpNper10_50=(ExpTotanNumberOfProjectsWon10_50L*100)/ExpTotanNumberOfProjects10_50L;
        }
        if(ExpTotanNumberOfProjects51_150L>0){
        
              ExpNper51_150=(ExpTotanNumberOfProjectsWon51_150L*100)/ExpTotanNumberOfProjects51_150L;
        }
        if(ExpTotanNumberOfProjects151_350L>0){
        
              ExpNper151_350=(ExpTotanNumberOfProjectsWon151_350L*100)/ExpTotanNumberOfProjects151_350L;
        }
        if(ExpTotanNumberOfProjects351_700L>0){
        
              ExpNper351_700=(ExpTotanNumberOfProjectsWon351_700L*100)/ExpTotanNumberOfProjects351_700L;
        }
        if(ExpTotanNumberOfProjectsGreaterThan700L>0){
        
              ExpNpergtr700=(ExpTotanNumberOfProjectsWonGreaterThan700L*100)/ExpTotanNumberOfProjectsGreaterThan700L;
        }
        
         //---------------------------------------------------------- for calculating percentage of submitted  Vs Won for Domestic----------------------------   
        if(DomQuotesSubmitted>0){
        
           DomTotalper=(DomOrdersWon*100)/DomQuotesSubmitted;
        }
        if(DomQuotesSubmitted0_10L>0){
        
             Domper0_10=(DomOrderWon0_10*100)/DomQuotesSubmitted0_10L;
        }
         if(DomQuotesSubmitted10_50L>0){
        
             Domper10_50=(DomOrderWon10_50*100)/DomQuotesSubmitted10_50L;
        }
        if(DomQuotesSubmitted51_150L>0){
        
             Domper51_150=(DomOrderWon51_150*100)/DomQuotesSubmitted51_150L;
        }
        if(DomQuotesSubmitted151_350L>0){
        
             Domper151_350=(DomOrderWon151_350*100)/DomQuotesSubmitted151_350L;
        }
        if(DomQuotesSubmitted351_700L>0){
        
            Domper351_700=(DomOrderWon351_700*100)/DomQuotesSubmitted351_700L;
        }
        if(DomQuotesSubmittedGreaterThan700L>0){
        
             Dompergtr700=(DomOrderWonGreaterThan700L*100)/DomQuotesSubmittedGreaterThan700L;
        }
      //---------------------------------------------------------percentage of no of project submitted Vs Won for Export---------------------------
      
        if(DomTotanNumberOfProjects>0){
        
              DomNTotalper=(DomTotanNumberOfProjectsWon*100)/DomTotanNumberOfProjects;
        }
        if(DomTotanNumberOfProjects0_10L>0){
        
              DomNper0_10=(DomTotanNumberOfProjectsWon0_10L*100)/DomTotanNumberOfProjects0_10L;
        }
        if(DomTotanNumberOfProjects10_50L>0){
        
              DomNper10_50=(DomTotanNumberOfProjectsWon10_50L*100)/DomTotanNumberOfProjects10_50L;
        }
        if(DomTotanNumberOfProjects51_150L>0){
        
              DomNper51_150=(DomTotanNumberOfProjectsWon51_150L*100)/DomTotanNumberOfProjects51_150L;
        }
        if(DomTotanNumberOfProjects151_350L>0){
        
              DomNper151_350=(DomTotanNumberOfProjectsWon151_350L*100)/DomTotanNumberOfProjects151_350L;
        }
        if(DomTotanNumberOfProjects351_700L>0){
        
              DomNper351_700=(DomTotanNumberOfProjectsWon351_700L*100)/DomTotanNumberOfProjects351_700L;
        }
        if(DomTotanNumberOfProjectsGreaterThan700L>0){
        
              DomNpergtr700=(DomTotanNumberOfProjectsWonGreaterThan700L*100)/DomTotanNumberOfProjectsGreaterThan700L;
        }
        
        //---------------------------------------------------------- for calculating percentage of submitted  Vs Won for Existing----------------------------   
        if(ExiQuotesSubmitted>0){
        
           ExiTotalper=(ExiOrdersWon*100)/ExiQuotesSubmitted;
        }
        if(ExiQuotesSubmitted0_10L>0){
        
             Exiper0_10=(ExiOrderWon0_10*100)/ExiQuotesSubmitted0_10L;
        }
         if(ExiQuotesSubmitted10_50L>0){
        
             Exiper10_50=(ExiOrderWon10_50*100)/ExiQuotesSubmitted10_50L;
        }
        if(ExiQuotesSubmitted51_150L>0){
        
             Exiper51_150=(ExiOrderWon51_150*100)/ExiQuotesSubmitted51_150L;
        }
        if(ExiQuotesSubmitted151_350L>0){
        
             Exiper151_350=(ExiOrderWon151_350*100)/ExiQuotesSubmitted151_350L;
        }
        if(ExiQuotesSubmitted351_700L>0){
        
            Exiper351_700=(ExiOrderWon351_700*100)/ExiQuotesSubmitted351_700L;
        }
        if(ExiQuotesSubmittedGreaterThan700L>0){
        
             Exipergtr700=(ExiOrderWonGreaterThan700L*100)/ExiQuotesSubmittedGreaterThan700L;
        }
      //---------------------------------------------------------percentage of no of project submitted Vs Won---------------------------
      
        if(ExiTotanNumberOfProjects>0){
        
              ExiNTotalper=(ExiTotanNumberOfProjectsWon*100)/ExiTotanNumberOfProjects;
        }
        if(ExiTotanNumberOfProjects0_10L>0){
        
              ExiNper0_10=(ExiTotanNumberOfProjectsWon0_10L*100)/ExiTotanNumberOfProjects0_10L;
        }
        if(ExiTotanNumberOfProjects10_50L>0){
        
              ExiNper10_50=(ExiTotanNumberOfProjectsWon10_50L*100)/ExiTotanNumberOfProjects10_50L;
        }
        if(ExiTotanNumberOfProjects51_150L>0){
        
              ExiNper51_150=(ExiTotanNumberOfProjectsWon51_150L*100)/ExiTotanNumberOfProjects51_150L;
        }
        if(ExiTotanNumberOfProjects151_350L>0){
        
              ExiNper151_350=(ExiTotanNumberOfProjectsWon151_350L*100)/ExiTotanNumberOfProjects151_350L;
        }
        if(ExiTotanNumberOfProjects351_700L>0){
        
              ExiNper351_700=(ExiTotanNumberOfProjectsWon351_700L*100)/ExiTotanNumberOfProjects351_700L;
        }
        if(ExiTotanNumberOfProjectsGreaterThan700L>0){
        
              ExiNpergtr700=(ExiTotanNumberOfProjectsWonGreaterThan700L*100)/ExiTotanNumberOfProjectsGreaterThan700L;
        }
        
        //---------------------------------------------------------- for calculating percentage of submitted  Vs Won New----------------------------   
        if(NewQuotesSubmitted>0){
        
           NewTotalper=(NewOrdersWon*100)/NewQuotesSubmitted;
        }
        if(NewQuotesSubmitted0_10L>0){
        
             Newper0_10=(NewOrderWon0_10*100)/NewQuotesSubmitted0_10L;
        }
         if(NewQuotesSubmitted10_50L>0){
        
             Newper10_50=(NewOrderWon10_50*100)/NewQuotesSubmitted10_50L;
        }
        if(NewQuotesSubmitted51_150L>0){
        
             Newper51_150=(NewOrderWon51_150*100)/NewQuotesSubmitted51_150L;
        }
        if(NewQuotesSubmitted151_350L>0){
        
             Newper151_350=(NewOrderWon151_350*100)/NewQuotesSubmitted151_350L;
        }
        if(NewQuotesSubmitted351_700L>0){
        
            Newper351_700=(NewOrderWon351_700*100)/NewQuotesSubmitted351_700L;
        }
        if(NewQuotesSubmittedGreaterThan700L>0){
        
             Newpergtr700=(NewOrderWonGreaterThan700L*100)/NewQuotesSubmittedGreaterThan700L;
        }
      //---------------------------------------------------------percentage of no of project submitted Vs Won---------------------------
      
        if(NewTotanNumberOfProjects>0){
        
              NewNTotalper=(NewTotanNumberOfProjectsWon*100)/NewTotanNumberOfProjects;
        }
        if(NewTotanNumberOfProjects0_10L>0){
        
              NewNper0_10=(NewTotanNumberOfProjectsWon0_10L*100)/NewTotanNumberOfProjects0_10L;
        }
        if(NewTotanNumberOfProjects10_50L>0){
        
              NewNper10_50=(NewTotanNumberOfProjectsWon10_50L*100)/NewTotanNumberOfProjects10_50L;
        }
        if(NewTotanNumberOfProjects51_150L>0){
        
              NewNper51_150=(NewTotanNumberOfProjectsWon51_150L*100)/NewTotanNumberOfProjects51_150L;
        }
        if(NewTotanNumberOfProjects151_350L>0){
        
              NewNper151_350=(NewTotanNumberOfProjectsWon151_350L*100)/NewTotanNumberOfProjects151_350L;
        }
        if(NewTotanNumberOfProjects351_700L>0){
        
              NewNper351_700=(NewTotanNumberOfProjectsWon351_700L*100)/NewTotanNumberOfProjects351_700L;
        }
        if(NewTotanNumberOfProjectsGreaterThan700L>0){
        
              NewNpergtr700=(NewTotanNumberOfProjectsWonGreaterThan700L*100)/NewTotanNumberOfProjectsGreaterThan700L;
        }
      
    }
    
    Public void Runreport(){
    lstOptions = new List<SelectOption>();
        
        lstOptions.add(new SelectOption('0',' - - - Select - - - '));
        lstOptions.add(new SelectOption('1','Current FY'));
        lstOptions.add(new SelectOption('2','Previous FY'));
        lstOptions.add(new SelectOption('3','Current FQ'));
        lstOptions.add(new SelectOption('4','Previous FQ'));
        lstOptions.add(new SelectOption('5','This Month'));
        lstOptions.add(new SelectOption('6','Last Month'));
        
        system.debug('@@@@'+ monthSelected);
    
  
    
        Quote_submitted=0;
        Still_active=0;
        Oppurtunity_on_hold=0;
        Projects_shelved=0;
        Awarded_PO_by_customer=0;
        Order_won=0;
        Lost_on_Cost=0;
        Lost_on_Lead_time=0;
        Lost_on_strategic_reasons=0;
        Regret=0;
        Overall=0;
        Overall1=0;
        
        PerQuote_submitted=0;
        PerStill_active=0;
        PerOppurtunity_on_hold=0;
        PerProjects_shelved=0;
        PerAwarded_PO_by_customer=0;
        PerOrder_won=0;
        PerLost_on_Cost=0;
        PerLost_on_Lead_time=0;
        PerLost_on_strategic_reasons=0;
        PerRegret=0;
        
        OWafunne=0;
        OWafunnee=0;
        OWrqsub=0;
        OWacfqt=0;
        OWqtprep=0;
        ACafunne=0;
        ACafunnee=0;
        ACundneg=0;
        ACrqsub=0;
        ACacfqt=0;
        ACqtprep=0;
        SAafunne=0;
        SAundneg=0;
        SArqsub=0;
        SAacfqt=0;
        SAqtprep=0;
        QSafunne=0;
        QSundneg=0;
        QSrqsub=0;
        QSacfqt=0;
        QSqtprep=0;
        
        OrdersWon=0;
        OrderWon0_10=0;
        OrderWon10_50=0;
        OrderWon51_150=0;
        OrderWon151_350=0;
        OrderWon351_700=0;
        OrderWonGreaterThan700L=0;
        
        QuotesSubmitted=0;
        QuotesSubmitted0_10L=0;
        QuotesSubmitted10_50L=0;
        QuotesSubmitted51_150L=0;
        QuotesSubmitted151_350L=0;
        QuotesSubmitted351_700L=0;
        QuotesSubmittedGreaterThan700L=0;
        
        Totalper=0;
        per0_10=0;
        per10_50=0;
        per51_150=0;
        per151_350=0;
        per351_700=0;
        pergtr700=0;
        
        ExpTotalper=0;
        Expper0_10=0;
        Expper10_50=0;
        Expper51_150=0;
        Expper151_350=0;
        Expper351_700=0;
        Exppergtr700=0;
        
        DomTotalper=0;
        Domper0_10=0;
        Domper10_50=0;
        Domper51_150=0;
        Domper151_350=0;
        Domper351_700=0;
        Dompergtr700=0;
        
        ExiTotalper=0;
        Exiper0_10=0;
        Exiper10_50=0;
        Exiper51_150=0;
        Exiper151_350=0;
        Exiper351_700=0;
        Exipergtr700=0;
        
        NewTotalper=0;
        Newper0_10=0;
        Newper10_50=0;
        Newper51_150=0;
        Newper151_350=0;
        Newper351_700=0;
        Newpergtr700=0;
            
        ExpOrdersWon=0;
        ExpOrderWon0_10=0;
        ExpOrderWon10_50=0;
        ExpOrderWon51_150=0;
        ExpOrderWon151_350=0;
        ExpOrderWon351_700=0;
        ExpOrderWonGreaterThan700L=0;
        
        ExpQuotesSubmitted=0;
        ExpQuotesSubmitted0_10L=0;
        ExpQuotesSubmitted10_50L=0;
        ExpQuotesSubmitted51_150L=0;
        ExpQuotesSubmitted151_350L=0;
        ExpQuotesSubmitted351_700L=0;
        ExpQuotesSubmittedGreaterThan700L=0;
        
        
        DomOrdersWon=0;
        DomOrderWon0_10=0;
        DomOrderWon10_50=0;
        DomOrderWon51_150=0;
        DomOrderWon151_350=0;
        DomOrderWon351_700=0;
        DomOrderWonGreaterThan700L=0;
        
        DomQuotesSubmitted=0;
        DomQuotesSubmitted0_10L=0;
        DomQuotesSubmitted10_50L=0;
        DomQuotesSubmitted51_150L=0;
        DomQuotesSubmitted151_350L=0;
        DomQuotesSubmitted351_700L=0;
        DomQuotesSubmittedGreaterThan700L=0;
        
        
        ExiOrdersWon=0;
        ExiOrderWon0_10=0;
        ExiOrderWon10_50=0;
        ExiOrderWon51_150=0;
        ExiOrderWon151_350=0;
        ExiOrderWon351_700=0;
        ExiOrderWonGreaterThan700L=0;
        
        ExiQuotesSubmitted=0;
        ExiQuotesSubmitted0_10L=0;
        ExiQuotesSubmitted10_50L=0;
        ExiQuotesSubmitted51_150L=0;
        ExiQuotesSubmitted151_350L=0;
        ExiQuotesSubmitted351_700L=0;
        ExiQuotesSubmittedGreaterThan700L=0;
        
        
        NewOrdersWon=0;
        NewOrderWon0_10=0;
        NewOrderWon10_50=0;
        NewOrderWon51_150=0;
        NewOrderWon151_350=0;
        NewOrderWon351_700=0;
        NewOrderWonGreaterThan700L=0;
        
        NewQuotesSubmitted=0;
        NewQuotesSubmitted0_10L=0;
        NewQuotesSubmitted10_50L=0;
        NewQuotesSubmitted51_150L=0;
        NewQuotesSubmitted151_350L=0;
        NewQuotesSubmitted351_700L=0;
        NewQuotesSubmittedGreaterThan700L=0;
        
        oplisttemp=new List<opportunity>();
        
         
        TotanNumberOfProjects=0;
        TotanNumberOfProjects0_10L=0;
        TotanNumberOfProjects10_50L=0;
        TotanNumberOfProjects51_150L=0;
        TotanNumberOfProjects151_350L=0;
        TotanNumberOfProjects351_700L=0;
        TotanNumberOfProjectsGreaterThan700L=0;
        
        TotanNumberOfProjectsWon=0;
        TotanNumberOfProjectsWon0_10L=0;
        TotanNumberOfProjectsWon10_50L=0;
        TotanNumberOfProjectsWon51_150L=0;
        TotanNumberOfProjectsWon151_350L=0;
        TotanNumberOfProjectsWon351_700L=0;
        TotanNumberOfProjectsWonGreaterThan700L=0;
    
    
        ExpTotanNumberOfProjects=0;
        ExpTotanNumberOfProjects0_10L=0;
        ExpTotanNumberOfProjects10_50L=0;
        ExpTotanNumberOfProjects51_150L=0;
        ExpTotanNumberOfProjects151_350L=0;
        ExpTotanNumberOfProjects351_700L=0;
        ExpTotanNumberOfProjectsGreaterThan700L=0;
        
        ExpTotanNumberOfProjectsWon=0;
        ExpTotanNumberOfProjectsWon0_10L=0;
        ExpTotanNumberOfProjectsWon10_50L=0;
        ExpTotanNumberOfProjectsWon51_150L=0;
        ExpTotanNumberOfProjectsWon151_350L=0;
        ExpTotanNumberOfProjectsWon351_700L=0;
        ExpTotanNumberOfProjectsWonGreaterThan700L=0;
        
        
        DomTotanNumberOfProjects=0;
        DomTotanNumberOfProjects0_10L=0;
        DomTotanNumberOfProjects10_50L=0;
        DomTotanNumberOfProjects51_150L=0;
        DomTotanNumberOfProjects151_350L=0;
        DomTotanNumberOfProjects351_700L=0;
        DomTotanNumberOfProjectsGreaterThan700L=0;
        
        DomTotanNumberOfProjectsWon=0;
        DomTotanNumberOfProjectsWon0_10L=0;
        DomTotanNumberOfProjectsWon10_50L=0;
        DomTotanNumberOfProjectsWon51_150L=0;
        DomTotanNumberOfProjectsWon151_350L=0;
        DomTotanNumberOfProjectsWon351_700L=0;
        DomTotanNumberOfProjectsWonGreaterThan700L=0;
        
        ExiTotanNumberOfProjects=0;
        ExiTotanNumberOfProjects0_10L=0;
        ExiTotanNumberOfProjects10_50L=0;
        ExiTotanNumberOfProjects51_150L=0;
        ExiTotanNumberOfProjects151_350L=0;
        ExiTotanNumberOfProjects351_700L=0;
        ExiTotanNumberOfProjectsGreaterThan700L=0;
        
        ExiTotanNumberOfProjectsWon=0;
        ExiTotanNumberOfProjectsWon0_10L=0;
        ExiTotanNumberOfProjectsWon10_50L=0;
        ExiTotanNumberOfProjectsWon51_150L=0;
        ExiTotanNumberOfProjectsWon151_350L=0;
        ExiTotanNumberOfProjectsWon351_700L=0;
        ExiTotanNumberOfProjectsWonGreaterThan700L=0;
        
        
        NewTotanNumberOfProjects=0;
        NewTotanNumberOfProjects0_10L=0;
        NewTotanNumberOfProjects10_50L=0;
        NewTotanNumberOfProjects51_150L=0;
        NewTotanNumberOfProjects151_350L=0;
        NewTotanNumberOfProjects351_700L=0;
        NewTotanNumberOfProjectsGreaterThan700L=0;
        
        NewTotanNumberOfProjectsWon=0;
        NewTotanNumberOfProjectsWon0_10L=0;
        NewTotanNumberOfProjectsWon10_50L=0;
        NewTotanNumberOfProjectsWon51_150L=0;
        NewTotanNumberOfProjectsWon151_350L=0;
        NewTotanNumberOfProjectsWon351_700L=0;
        NewTotanNumberOfProjectsWonGreaterThan700L=0;
       
        /*-------------------------fatching Record type id for Account and opportunity-------------------------*/
        ID RtAccountMBA;
        ID RtIdAllocatedRecordType;
        ID RtIdAwaitFeedbackRecordType;
        ID RtIdInitialRecordtype;
        ID RtIdLayoutRecordType;
        ID RtIdMBA;
        ID RtIdMBAServicesAllocated;
        ID RtIdMBAServicesFinal;
        ID RtIdMBASparesFinal;
        ID RtIdPECSA;
        ID RtIdQuoteSubmittedRecordType;
        ID RtIdQuoteSubmittedServices;
        ID RtIdQuoteSubmittedSpares;
        ID RtIdRegretMBARecordType;
        ID RtIdSpareServicesRecordType;
        /*----------------------------------fatching account record type id------------------------------------------------*/
       List<RecordType> AccountRt = [select name,id from RecordType where Sobjecttype='Account'];
       for(RecordType ActRt: AccountRt)
       {
            if(ActRt.name=='MBA')
            {
                RtAccountMBA=ActRt.id;
                
            }
           
       }
        
        /*--------------------------------------------fatching opportunity reocrdtype id------------------------------------*/
        List<RecordType> Rt = [select name,id from RecordType where Sobjecttype='Opportunity'];  
        for(RecordType Rtype : Rt)
        {

            if(Rtype.name=='Allocated Record Type')
            {
                RtIdAllocatedRecordType = Rtype.id;
            }
            if(Rtype.name=='Await Feedback Record Type')
            {
                RtIdAwaitFeedbackRecordType = Rtype.id;
            }
            if(Rtype.name=='Initial Record type')
            {
                RtIdInitialRecordtype = Rtype.id;
            }
            if(Rtype.name=='Layout Record Type')
            {
                RtIdLayoutRecordType = Rtype.id;
            }
            if(Rtype.name=='MBA')
            {
                RtIdMBA = Rtype.id;
            }
            if(Rtype.name=='MBA Services Allocated')
            {
                RtIdMBAServicesAllocated = Rtype.id;
            }
            if(Rtype.name=='MBA Services Final')
            {
                RtIdMBAServicesFinal = Rtype.id;
            }
            if(Rtype.name=='MBA Spares Final')
            {
                RtIdMBASparesFinal = Rtype.id;
            }
            if(Rtype.name=='PECSA')
            {
                RtIdPECSA = Rtype.id;
            }
            if(Rtype.name=='Quote Submitted Record Type')
            {
                RtIdQuoteSubmittedRecordType = Rtype.id; 
            }
            if(Rtype.name=='Quote Submitted Services')
            {
                RtIdQuoteSubmittedServices = Rtype.id;
            }
            if(Rtype.name=='Quote Submitted Spares')
            {
                RtIdQuoteSubmittedSpares = Rtype.id;
            }
            if(Rtype.name=='Regret MBA Record Type')
            {
                RtIdRegretMBARecordType = Rtype.id;
            }
            if(Rtype.name=='Spares & Services Record Type')
            {
                RtIdSpareServicesRecordType = Rtype.id;
            }
        }
     List<Quote> QuoteList=new List <Quote> ();
     if(fromdate == null)
     {
       
            if(monthSelected=='1')
            {
                OpIdList = new set<ID>();
                QuoteList  = new List <Quote> ();
                system.debug('!!!!!!!!THIS_FISCAL_YEAR!!!!!!!');
                QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= THIS_FISCAL_YEAR];
            }
            
            if(monthSelected=='2')
            {  
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!LAST_FISCAL_YEAR!!!!!!!');
                QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= LAST_FISCAL_YEAR];
                System.debug('*********************************************************quote*******************************************'+QuoteList);
            }
            
            if(monthSelected=='3')
            {  
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!THIS_FISCAL_QUARTER!!!!!!!');
                 QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= THIS_FISCAL_QUARTER];
            }
            
            if(monthSelected=='4')
            {
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!LAST_FISCAL_QUARTER!!!!!!!');
                QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= LAST_FISCAL_QUARTER ];
            }
            
            if(monthSelected=='5')
            {
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!THIS_MONTH!!!!!!!');
                QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= THIS_MONTH];
            }
            
            if(monthSelected=='6')
            {
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!LAST_MONTH!!!!!!!');
                 QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c= LAST_MONTH];
            }
                 
     }
    else{
                OpIdList = new set<ID>();
                QuoteList= new List <Quote> ();
                system.debug('!!!!!!!!LAST_MONTH!!!!!!!');
                 QuoteList = [select OpportunityId,CreatedDate from Quote where Is_Synched__c =:'Yes' AND Opportunity.Account.RecordTypeId=:RtAccountMBA AND Opportunity.First_Quote_Created_Date__c >= :fromdate AND Opportunity.First_Quote_Created_Date__c <= :todate];
            dateformat = true;
    }
    
       
        for(Quote Q : QuoteList)
        {
            OpIdList.add(Q.OpportunityId); 
        }
        System.debug('*********************************************oppId*******************************************************'+OpIdList);
        List<opportunity> oplist =[select id,StageName,name,Converted_Amount__c ,Project_Type__c,Customer_Type__c,RecordTypeId,RecordType.Name,Account.RecordTypeId,Amount,Reason__c,Cost_band__c from opportunity where id in: OpIdList];
      
        
        
        for(Opportunity op : oplist)
         {
         if((op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
              op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
         
             system.debug('-----------------------For 1st Dashboard----------------');
             
            if(op.StageName=='Await Customer Feedback(Quote Submitted)' || op.StageName=='Revised Quote Submission'
                ||op.StageName=='Under Negotiation' || op.StageName=='Await Feedback (Under Negotiation)'||op.StageName=='Order Won'
                ||op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Opportunity On Hold' || op.StageName=='Opportunity Lost' || op.StageName=='Project Cancelled'
                ||op.StageName=='Project On Hold')
            {
                Quote_submitted=Quote_submitted+op.Amount;
                if(op.StageName=='Quote Preparation')
                {
                    QSqtprep=QSqtprep+op.Amount;
                }
                if(op.StageName=='Await Customer Feedback(Quote Submitted)')
                {
                    QSacfqt=QSacfqt+op.Amount;
                }
                if(op.StageName=='Revised Quote Submission')
                {
                    QSrqsub=QSrqsub+op.Amount;
                }
                if(op.StageName=='Under Negotiation')
                {
                    QSundneg=QSundneg+op.Amount;
                }
                if(op.StageName=='Await Feedback (Under Negotiation)')
                {
                    QSafunne=QSafunne+op.Amount;
                }
                
            }
            
            if(op.StageName=='Await Customer Feedback(Quote Submitted)' || op.StageName=='Revised Quote Submission'
                ||op.StageName=='Under Negotiation' || op.StageName=='Await Feedback (Under Negotiation)')
            {
                Still_active=Still_active+op.Amount;
                if(op.StageName=='Quote Preparation')
                {
                    SAqtprep=SAqtprep+op.Amount;
                }
                if(op.StageName=='Await Customer Feedback(Quote Submitted)')
                {
                    SAacfqt=SAacfqt+op.Amount;
                }
                if(op.StageName=='Revised Quote Submission')
                {
                    SArqsub=SArqsub+op.Amount;
                }
                if(op.StageName=='Under Negotiation')
                {
                    SAundneg=SAundneg+op.Amount;
                }
                if(op.StageName=='Await Feedback (Under Negotiation)')
                {
                    SAafunne=SAafunne+op.Amount;
                }
            }
            
            if(op.StageName=='Opportunity On Hold')
            {
                Oppurtunity_on_hold=Oppurtunity_on_hold+op.Amount;
            }
            /*if(op.Reason__c=='Project Shelved')
            {
                Projects_shelved=Projects_shelved+op.Amount;
            }*/
            if(op.Reason__c !='Project Shelved' && op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed'  
            || op.StageName=='Opportunity Lost' || op.StageName=='Project On Hold'|| op.StageName=='Project Cancelled')
            {
                Awarded_PO_by_customer=Awarded_PO_by_customer+op.Amount;
                if(op.StageName=='Order Won')
                {
                    ACqtprep=ACqtprep+op.Amount;
                }
                if(op.StageName=='Project Under Execution' )
                {
                    ACacfqt=ACacfqt+op.Amount;
                }
                if(op.StageName=='Project Closed')
                {
                    ACrqsub=ACrqsub+op.Amount;
                }
                if(op.StageName=='Opportunity Lost')
                {
                    ACundneg=ACundneg+op.Amount;
                }
                if(op.StageName=='Project On Hold')
                {
                    ACafunne=ACafunne+op.Amount;
                }
                if(op.StageName=='Project Cancelled')
                {
                    ACafunnee=ACafunnee+op.Amount;
                }
            }
            if(op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed'|| op.StageName=='Project On Hold'|| op.StageName=='Project Cancelled')
            {
                Order_won=Order_won+op.Amount;
                if(op.StageName=='Order Won')
                {
                    OWqtprep=OWqtprep+op.Amount;
                }
                if(op.StageName=='Project Under Execution' )
                {
                    OWacfqt=OWacfqt+op.Amount;
                }
                if(op.StageName=='Project Closed')
                {
                    OWrqsub=OWrqsub+op.Amount;
                }
                
                if(op.StageName=='Project On Hold')
                {
                    OWafunne=OWafunne+op.Amount;
                }
                if(op.StageName=='Project Cancelled')
                {
                    OWafunnee=OWafunnee+op.Amount;
                }
            }
            if(op.Reason__c=='Lost on cost' ||op.Reason__c=='High Price')
            {
              
                Lost_on_Cost=Lost_on_Cost+op.Amount;
                
            }
            if(op.Reason__c=='Lost on lead time')
            {
                Lost_on_Lead_time=Lost_on_Lead_time+op.Amount;
            }
            if(op.Reason__c=='Lost on strategic reason')
            {
                Lost_on_strategic_reasons=Lost_on_strategic_reasons+op.Amount;
            }
            if(op.Reason__c=='Regret')
            {
                Regret=Regret+op.Amount;
            }
         }
         }
         Regret=Regret/100000;
         Lost_on_strategic_reasons=Lost_on_strategic_reasons/100000;
         Lost_on_Lead_time=Lost_on_Lead_time/100000;
         Lost_on_Cost=Lost_on_Cost/100000;
         Order_won=Order_won/100000;
         Awarded_PO_by_customer=Awarded_PO_by_customer/100000;
         Projects_shelved=Projects_shelved/100000;
         Oppurtunity_on_hold=Oppurtunity_on_hold/100000;
         Still_active=Still_active/100000;
         Quote_submitted=Quote_submitted/100000;
         
         Overall=Awarded_PO_by_customer+Projects_shelved+Oppurtunity_on_hold+Still_active;
         Overall1=Regret+Lost_on_strategic_reasons+Lost_on_Lead_time+Lost_on_Cost+Order_won;
         
          if(Overall !=0 && Overall1 !=0){
        //PerAwarded_PO_by_customer=(Awarded_PO_by_customer/Overall1)*100;
        PerOrder_won=(Order_won/Overall1)*100;
        PerLost_on_Cost=(Lost_on_Cost/Overall1)*100;
        PerLost_on_Lead_time=(Lost_on_Lead_time/Overall1)*100;
        PerLost_on_strategic_reasons=(Lost_on_strategic_reasons/Overall1)*100;
        PerRegret=(Regret/Overall1)*100;
        PerAwarded_PO_by_customer=(Awarded_PO_by_customer/Overall)*100;
        
        PerStill_active=(Still_active/Overall)*100;
        PerOppurtunity_on_hold=(Oppurtunity_on_hold/Overall)*100;
        PerProjects_shelved=(Projects_shelved/Overall)*100;
        //PerQuote_submitted=(Quote_submitted/Overall)*100;
        PerQuote_submitted = PerAwarded_PO_by_customer+PerStill_active+PerOppurtunity_on_hold+PerProjects_shelved;
         }
         
         system.debug('$$$$$$$$Overall$$$$$$$$$$$'+Overall);
         system.debug('$$$$$$$$$Overall1$$$$$$$$$$'+Overall1);
         system.debug('$$$$$$$$Quote_submitted$$$$$$$$$$$'+Quote_submitted);
         system.debug('$$$$$$$$$Still_active$$$$$$$$$$'+Still_active);
         system.debug('$$$$$$$$$Oppurtunity_on_hold$$$$$$$$$$'+Oppurtunity_on_hold);
         system.debug('$$$$$$$$Projects_shelved$$$$$$$$$$$'+Projects_shelved);
         system.debug('$$$$$$$$$Awarded_PO_by_customer$$$$$$$$$$'+Awarded_PO_by_customer);
         system.debug('$$$$$$$$$Order_won$$$$$$$$$$'+Order_won);
         system.debug('$$$$$$$$Lost_on_Cost$$$$$$$$$$$'+Lost_on_Cost);
         system.debug('$$$$$$$$Lost_on_Lead_time$$$$$$$$$$$'+Lost_on_Lead_time);
         system.debug('$$$$$$$$$Lost_on_strategic_reasons$$$$$$$$$$'+Lost_on_strategic_reasons);
         system.debug('$$$$$$$$$Regret$$$$$$$$$$'+Regret);
       data= new List<Decimal>();
        
      
        
        data.add(Regret);
        data.add(Lost_on_strategic_reasons);
        data.add(Lost_on_Lead_time);
        data.add(Lost_on_Cost);
        data.add(Order_won);
        data.add(Awarded_PO_by_customer);
        data.add(Projects_shelved);
        data.add(Oppurtunity_on_hold);
        data.add(Still_active);
        data.add(Quote_submitted);
        
    
         
        for(Opportunity op : oplist)
         {
            if((op.Account.RecordTypeId==RtAccountMBA) &&(op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal &&
            op.RecordTypeId != RtIdMBASparesFinal && op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {            
                if(op.StageName=='Await Customer Feedback(Quote Submitted)' || op.StageName=='Revised Quote Submission'
                ||op.StageName=='Under Negotiation' || op.StageName=='Await Feedback (Under Negotiation)'||op.StageName=='Order Won'
                ||op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Opportunity On Hold' || op.StageName=='Opportunity Lost' || op.StageName=='Project Cancelled'
                ||op.StageName=='Project On Hold')
                {

                    /*---------------------------calculating QuotesSubmitted(Proposals Submitted - Win loss)---------------------------------------*/


                    system.debug('###################### In side Proposals Submitted - Win loss for all ################################');
                    TotanNumberOfProjects=TotanNumberOfProjects+1;
                    if(op.Amount!= null)
                    {
                    QuotesSubmitted=QuotesSubmitted+op.Amount;

                    }
                    if(op.Cost_band__c=='0-10L')
                    {   
                    TotanNumberOfProjects0_10L=TotanNumberOfProjects0_10L+1;
                    if(op.amount != null)
                    {
                    QuotesSubmitted0_10L = QuotesSubmitted0_10L + op.Amount;

                    }     
                    }         
                    if(op.Cost_band__c=='10-50L' || Test.isRunningTest())
                    {
                    TotanNumberOfProjects10_50L=TotanNumberOfProjects10_50L+1;
                    if(op.Amount != null)
                    {
                    QuotesSubmitted10_50L = QuotesSubmitted10_50L + op.Amount;

                    }
                    }
                    if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                    {
                    TotanNumberOfProjects51_150L=TotanNumberOfProjects51_150L+1;
                    if(op.Amount != Null)
                    {
                    QuotesSubmitted51_150L = QuotesSubmitted51_150L + op.Amount;

                    }
                    }
                    if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                    {
                    TotanNumberOfProjects151_350L=TotanNumberOfProjects51_150L+1;
                    if(op.Amount != Null)
                    {
                    QuotesSubmitted151_350L = QuotesSubmitted151_350L + op.Amount;

                    }
                    }
                    if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                    {
                    TotanNumberOfProjects351_700L=TotanNumberOfProjects351_700L+1;
                    if(op.Amount != Null)
                    {
                    QuotesSubmitted351_700L = QuotesSubmitted351_700L + op.Amount;

                    }
                    }
                    if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                    {
                    TotanNumberOfProjectsGreaterThan700L=TotanNumberOfProjectsGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                    QuotesSubmittedGreaterThan700L = QuotesSubmittedGreaterThan700L + op.Amount;

                    }    
                    }
                    
                    system.debug('*************************Out export Quote Submitted');



                    // for Export customer
                    if((op.Account.RecordTypeId==RtAccountMBA)&&(op.Project_Type__c =='Export'))
                    {
                        system.debug('###################### In side Proposals Submitted - Win loss for Export ################################');
                        ExpTotanNumberOfProjects=ExpTotanNumberOfProjects+1;
                        if(op.Amount!= null)
                        {
                        ExpQuotesSubmitted=ExpQuotesSubmitted+op.Amount;

                        }
                        if(op.Cost_band__c=='0-10L')
                        {   
                        ExpTotanNumberOfProjects0_10L=ExpTotanNumberOfProjects0_10L+1;
                        if(op.amount != null)
                        {
                        ExpQuotesSubmitted0_10L = ExpQuotesSubmitted0_10L + op.Amount;

                        }     
                        }         
                        if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                        {
                        ExpTotanNumberOfProjects10_50L=ExpTotanNumberOfProjects10_50L+1;
                        if(op.Amount != null)
                        {
                        ExpQuotesSubmitted10_50L = ExpQuotesSubmitted10_50L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                        {
                        ExpTotanNumberOfProjects51_150L=ExpTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        ExpQuotesSubmitted51_150L = ExpQuotesSubmitted51_150L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                        {
                        ExpTotanNumberOfProjects151_350L=ExpTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        ExpQuotesSubmitted151_350L = ExpQuotesSubmitted151_350L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                        {
                        ExpTotanNumberOfProjects351_700L=ExpTotanNumberOfProjects351_700L+1;
                        if(op.Amount != Null)
                        {
                        ExpQuotesSubmitted351_700L = ExpQuotesSubmitted351_700L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                        {
                        ExpTotanNumberOfProjectsGreaterThan700L=ExpTotanNumberOfProjectsGreaterThan700L+1;
                        if(op.Amount != null)
                        {
                        ExpQuotesSubmittedGreaterThan700L = ExpQuotesSubmittedGreaterThan700L + op.Amount;

                        }    
                        }
                    }



                    // for Domestic customer
                    if((op.Account.RecordTypeId==RtAccountMBA)&&(op.Project_Type__c =='Domestic'))
                    {
                        system.debug('###################### In side Proposals Submitted - Win loss for Domestic ################################');
                        DomTotanNumberOfProjects=DomTotanNumberOfProjects+1;
                        if(op.Amount!= null)
                        {
                        DomQuotesSubmitted=DomQuotesSubmitted+op.Amount;

                        }
                        if(op.Cost_band__c=='0-10L')
                        {   
                        DomTotanNumberOfProjects0_10L=DomTotanNumberOfProjects0_10L+1;
                        if(op.amount != null)
                        {
                        DomQuotesSubmitted0_10L = DomQuotesSubmitted0_10L + op.Amount;

                        }     
                        }         
                        if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                        {
                        DomTotanNumberOfProjects10_50L=DomTotanNumberOfProjects10_50L+1;
                        if(op.Amount != null)
                        {
                        DomQuotesSubmitted10_50L = DomQuotesSubmitted10_50L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                        {
                        DomTotanNumberOfProjects51_150L=DomTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        DomQuotesSubmitted51_150L = DomQuotesSubmitted51_150L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                        {
                        DomTotanNumberOfProjects151_350L=DomTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        DomQuotesSubmitted151_350L = DomQuotesSubmitted151_350L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                        {
                        DomTotanNumberOfProjects351_700L=DomTotanNumberOfProjects351_700L+1;
                        if(op.Amount != Null)
                        {
                        DomQuotesSubmitted351_700L = DomQuotesSubmitted351_700L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                        {
                        DomTotanNumberOfProjectsGreaterThan700L=DomTotanNumberOfProjectsGreaterThan700L+1;
                        if(op.Amount != null)
                        {
                        DomQuotesSubmittedGreaterThan700L = DomQuotesSubmittedGreaterThan700L + op.Amount;

                        }    
                        }
                    }


                    // for Existing Customer

                    if((op.Account.RecordTypeId==RtAccountMBA) && (op.Customer_Type__c=='Existing Customer') )
                    {
                        system.debug('###################### In side Proposals Submitted - Win loss for Existing ################################');
                        ExiTotanNumberOfProjects=ExiTotanNumberOfProjects+1;
                        if(op.Amount!= null)
                        {
                        ExiQuotesSubmitted=ExiQuotesSubmitted+op.Amount;

                        }
                        if(op.Cost_band__c=='0-10L')
                        {   
                        ExiTotanNumberOfProjects0_10L=ExiTotanNumberOfProjects0_10L+1;
                        if(op.amount != null)
                        {
                        ExiQuotesSubmitted0_10L = ExiQuotesSubmitted0_10L + op.Amount;

                        }     
                        }         
                        if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                        {
                        ExiTotanNumberOfProjects10_50L=ExiTotanNumberOfProjects10_50L+1;
                        if(op.Amount != null)
                        {
                        ExiQuotesSubmitted10_50L = ExiQuotesSubmitted10_50L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                        {
                        ExiTotanNumberOfProjects51_150L=ExiTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        ExiQuotesSubmitted51_150L = ExiQuotesSubmitted51_150L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                        {
                        ExiTotanNumberOfProjects151_350L=ExiTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        ExiQuotesSubmitted151_350L = ExiQuotesSubmitted151_350L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                        {
                        ExiTotanNumberOfProjects351_700L=ExiTotanNumberOfProjects351_700L+1;
                        if(op.Amount != Null)
                        {
                        ExiQuotesSubmitted351_700L = ExiQuotesSubmitted351_700L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                        {
                        ExiTotanNumberOfProjectsGreaterThan700L=ExiTotanNumberOfProjectsGreaterThan700L+1;
                        if(op.Amount != null)
                        {
                        ExiQuotesSubmittedGreaterThan700L = ExiQuotesSubmittedGreaterThan700L + op.Amount;

                        }    
                        }
                    }

                    // for New Customers

                    if((op.Account.RecordTypeId==RtAccountMBA) && (op.Customer_Type__c=='New') )
                    {
                        system.debug('###################### In side Proposals Submitted - Win loss for New ################################');
                        NewTotanNumberOfProjects=NewTotanNumberOfProjects+1;
                        if(op.Amount!= null)
                        {
                        NewQuotesSubmitted=NewQuotesSubmitted+op.Amount;

                        }
                        if(op.Cost_band__c=='0-10L')
                        {   
                        NewTotanNumberOfProjects0_10L=NewTotanNumberOfProjects0_10L+1;
                        if(op.amount != null)
                        {
                        NewQuotesSubmitted0_10L = NewQuotesSubmitted0_10L + op.Amount;

                        }     
                        }         
                        if(op.Cost_band__c=='10-50L'|| Test.isRunningTest())
                        {
                        NewTotanNumberOfProjects10_50L=NewTotanNumberOfProjects10_50L+1;
                        if(op.Amount != null)
                        {
                        NewQuotesSubmitted10_50L = NewQuotesSubmitted10_50L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='51-150L'|| Test.isRunningTest())
                        {
                        NewTotanNumberOfProjects51_150L=NewTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        NewQuotesSubmitted51_150L = NewQuotesSubmitted51_150L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='151-350L'|| Test.isRunningTest())
                        {
                        NewTotanNumberOfProjects151_350L=NewTotanNumberOfProjects51_150L+1;
                        if(op.Amount != Null)
                        {
                        NewQuotesSubmitted151_350L = NewQuotesSubmitted151_350L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='351-700L'|| Test.isRunningTest())
                        {
                        NewTotanNumberOfProjects351_700L=NewTotanNumberOfProjects351_700L+1;
                        if(op.Amount != Null)
                        {
                        NewQuotesSubmitted351_700L = NewQuotesSubmitted351_700L + op.Amount;

                        }
                        }
                        if(op.Cost_band__c=='Greater than 700 L'|| Test.isRunningTest())
                        {
                        NewTotanNumberOfProjectsGreaterThan700L=NewTotanNumberOfProjectsGreaterThan700L+1;
                        if(op.Amount != null)
                        {
                        NewQuotesSubmittedGreaterThan700L = NewQuotesSubmittedGreaterThan700L + op.Amount;

                        }    
                        }
                    }
                }
            }
        }          
         QuotesSubmitted=QuotesSubmitted/100000;
         QuotesSubmitted0_10L=QuotesSubmitted0_10L/100000;
         QuotesSubmitted10_50L=QuotesSubmitted10_50L/100000;
         QuotesSubmitted51_150L=QuotesSubmitted51_150L/100000;
         QuotesSubmitted151_350L=QuotesSubmitted151_350L/100000;
         QuotesSubmitted351_700L=QuotesSubmitted351_700L/100000;
         QuotesSubmittedGreaterThan700L=QuotesSubmittedGreaterThan700L/100000;
         
         ExpQuotesSubmitted=ExpQuotesSubmitted/100000;
         ExpQuotesSubmitted0_10L=ExpQuotesSubmitted0_10L/100000;
         ExpQuotesSubmitted10_50L=ExpQuotesSubmitted10_50L/100000;
         ExpQuotesSubmitted51_150L=ExpQuotesSubmitted51_150L/100000;
         ExpQuotesSubmitted151_350L=ExpQuotesSubmitted151_350L/100000;
         ExpQuotesSubmitted351_700L=ExpQuotesSubmitted351_700L/100000;
         ExpQuotesSubmittedGreaterThan700L=ExpQuotesSubmittedGreaterThan700L/100000;
         
         DomQuotesSubmitted=DomQuotesSubmitted/100000;
         DomQuotesSubmitted0_10L=DomQuotesSubmitted0_10L/100000;
         DomQuotesSubmitted10_50L=DomQuotesSubmitted10_50L/100000;
         DomQuotesSubmitted51_150L=DomQuotesSubmitted51_150L/100000;
         DomQuotesSubmitted151_350L=DomQuotesSubmitted151_350L/100000;
         DomQuotesSubmitted351_700L=DomQuotesSubmitted351_700L/100000;
         DomQuotesSubmittedGreaterThan700L=DomQuotesSubmittedGreaterThan700L/100000;

         ExiQuotesSubmitted=ExiQuotesSubmitted/100000;
         ExiQuotesSubmitted0_10L=ExiQuotesSubmitted0_10L/100000;
         ExiQuotesSubmitted10_50L=ExiQuotesSubmitted10_50L/100000;
         ExiQuotesSubmitted51_150L=ExiQuotesSubmitted51_150L/100000;
         ExiQuotesSubmitted151_350L=ExiQuotesSubmitted151_350L/100000;
         ExiQuotesSubmitted351_700L=ExiQuotesSubmitted351_700L/100000;
         ExiQuotesSubmittedGreaterThan700L=ExiQuotesSubmittedGreaterThan700L/100000;
         
      
         
         NewQuotesSubmitted=NewQuotesSubmitted/100000;
         NewQuotesSubmitted0_10L=NewQuotesSubmitted0_10L/100000;
         NewQuotesSubmitted10_50L=NewQuotesSubmitted10_50L/100000;
         NewQuotesSubmitted51_150L=NewQuotesSubmitted51_150L/100000;
         NewQuotesSubmitted151_350L=NewQuotesSubmitted151_350L/100000;
         NewQuotesSubmitted351_700L=NewQuotesSubmitted351_700L/100000;
         NewQuotesSubmittedGreaterThan700L=NewQuotesSubmittedGreaterThan700L/100000;
       
         
         Decimal rounded = Math.round(QuotesSubmitted);
         Decimal rounded1 = Math.round(QuotesSubmitted0_10L);
         Decimal rounded2 = Math.round(QuotesSubmitted10_50L);
         Decimal rounded3 = Math.round(QuotesSubmitted51_150L);
         Decimal rounded4 = Math.round(QuotesSubmitted151_350L);
         Decimal rounded5 = Math.round(QuotesSubmitted351_700L);
         Decimal rounded6 = Math.round(QuotesSubmittedGreaterThan700L);
         
        
         /*--------------------------------------------------Calculating Orders Won------------------------------------------------------------*/
         List<opportunity> oplistForOrdersWon =[select id,name,StageName,Project_Type__c,Customer_Type__c,Converted_Amount__c ,RecordTypeId,RecordType.Name,Account.RecordTypeId,Amount, Cost_band__c from opportunity where (id in : OpIdList) ]; 
         
         for(Opportunity op : oplistForOrdersWon )
         {
            if((op.Account.RecordTypeId==RtAccountMBA) && 
            (op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Project Cancelled'|| op.StageName=='Project On Hold') && 
             
             (op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
              op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
             system.debug('###################### In side Orders Won for all ################################');
                oplisttemp.add(op);
                TotanNumberOfProjectsWon=TotanNumberOfProjectsWon+1;
                if(op.Cost_band__c=='0-10L')
                {   
                    TotanNumberOfProjectsWon0_10L=TotanNumberOfProjectsWon0_10L+1;
                    if(op.amount != null)
                    {
                        OrderWon0_10 = OrderWon0_10 + op.Amount;
                    }     
                }         
                if(op.Cost_band__c=='10-50L')
                {
                    TotanNumberOfProjectsWon10_50L=TotanNumberOfProjectsWon10_50L+1;
                    if(op.Amount != null)
                    {
                        OrderWon10_50 = OrderWon10_50 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='51-150L')
                {
                    TotanNumberOfProjectsWon51_150L=TotanNumberOfProjectsWon51_150L+1;
                    if(op.Amount != Null)
                    {
                        OrderWon51_150 = OrderWon51_150 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='151-350L')
                {
                    TotanNumberOfProjectsWon151_350L=TotanNumberOfProjectsWon151_350L+1;
                    if(op.Amount != Null)
                    {
                        OrderWon151_350 = OrderWon151_350 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='351-700L')
                {
                    TotanNumberOfProjectsWon351_700L=TotanNumberOfProjectsWon351_700L+1;
                    if(op.Amount != Null)
                    {
                        OrderWon351_700 = OrderWon351_700 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='Greater than 700 L')
                {
                    TotanNumberOfProjectsWonGreaterThan700L=TotanNumberOfProjectsWonGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                        OrderWonGreaterThan700L = OrderWonGreaterThan700L + op.Amount;
                    }    
                }
                if(op.Amount != null)
                {
                    OrdersWon = OrdersWon + op.Amount;
                }  
            }
            system.debug('*************************out export order won');
       
       
       // ----------------------------------------------for Export customer--------------------------------------------------------
            if((op.Account.RecordTypeId==RtAccountMBA)&&(op.Project_Type__c == 'Export')&&
            (op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Project Cancelled'|| op.StageName=='Project On Hold') && 
             
                    (op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
                    op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
            
               system.debug('###################### In side Orders Won for Export ################################');
                oplisttemp.add(op);
                ExpTotanNumberOfProjectsWon=ExpTotanNumberOfProjectsWon+1;
                if(op.Cost_band__c=='0-10L')
                {   
                    ExpTotanNumberOfProjectsWon0_10L=ExpTotanNumberOfProjectsWon0_10L+1;
                    if(op.amount != null)
                    {
                        ExpOrderWon0_10 = ExpOrderWon0_10 + op.Amount;
                    }     
                }         
                if(op.Cost_band__c=='10-50L')
                {
                    ExpTotanNumberOfProjectsWon10_50L=ExpTotanNumberOfProjectsWon10_50L+1;
                    if(op.Amount != null)
                    {
                        ExpOrderWon10_50 = ExpOrderWon10_50 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='51-150L')
                {
                    ExpTotanNumberOfProjectsWon51_150L=ExpTotanNumberOfProjectsWon51_150L+1;
                    if(op.Amount != Null)
                    {
                        ExpOrderWon51_150 = ExpOrderWon51_150 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='151-350L')
                {
                    ExpTotanNumberOfProjectsWon151_350L=ExpTotanNumberOfProjectsWon151_350L+1;
                    if(op.Amount != Null)
                    {
                        ExpOrderWon151_350 = ExpOrderWon151_350 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='351-700L')
                {
                    ExpTotanNumberOfProjectsWon351_700L=ExpTotanNumberOfProjectsWon351_700L+1;
                    if(op.Amount != Null)
                    {
                        ExpOrderWon351_700 = ExpOrderWon351_700 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='Greater than 700 L')
                {
                    ExpTotanNumberOfProjectsWonGreaterThan700L=ExpTotanNumberOfProjectsWonGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                        ExpOrderWonGreaterThan700L = ExpOrderWonGreaterThan700L + op.Amount;
                    }    
                }
                if(op.Amount != null)
                {
                    ExpOrdersWon = ExpOrdersWon + op.Amount;
                }  
            }   
    
    
    // -------------------------------------for Domestic customer-------------------------------------------------------------
            if((op.Account.RecordTypeId==RtAccountMBA)&&(op.Project_Type__c == 'Domestic')&&
            (op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Project Cancelled'|| op.StageName=='Project On Hold') && 
             
                    (op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
                    op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
            
                system.debug('###################### In side Orders Won for Domestic ################################');
                oplisttemp.add(op);
                DomTotanNumberOfProjectsWon=DomTotanNumberOfProjectsWon+1;
                if(op.Cost_band__c=='0-10L')
                {   
                    DomTotanNumberOfProjectsWon0_10L=DomTotanNumberOfProjectsWon0_10L+1;
                    if(op.amount != null)
                    {
                        DomOrderWon0_10 = DomOrderWon0_10 + op.Amount;
                    }     
                }         
                if(op.Cost_band__c=='10-50L')
                {
                    DomTotanNumberOfProjectsWon10_50L=DomTotanNumberOfProjectsWon10_50L+1;
                    if(op.Amount != null)
                    {
                        DomOrderWon10_50 = DomOrderWon10_50 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='51-150L')
                {
                    DomTotanNumberOfProjectsWon51_150L=DomTotanNumberOfProjectsWon51_150L+1;
                    if(op.Amount != Null)
                    {
                        DomOrderWon51_150 = DomOrderWon51_150 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='151-350L')
                {
                    DomTotanNumberOfProjectsWon151_350L=DomTotanNumberOfProjectsWon151_350L+1;
                    if(op.Amount != Null)
                    {
                        DomOrderWon151_350 = DomOrderWon151_350 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='351-700L')
                {
                    DomTotanNumberOfProjectsWon351_700L=DomTotanNumberOfProjectsWon351_700L+1;
                    if(op.Amount != Null)
                    {
                        DomOrderWon351_700 = DomOrderWon351_700 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='Greater than 700 L')
                {
                    DomTotanNumberOfProjectsWonGreaterThan700L=DomTotanNumberOfProjectsWonGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                        DomOrderWonGreaterThan700L = DomOrderWonGreaterThan700L + op.Amount;
                    }    
                }
                if(op.Amount != null)
                {
                    DomOrdersWon = DomOrdersWon + op.Amount;
                }  
            }   
            
    //------------------------------------------ for Existing customers---------------------------------------------------

                if((op.Account.RecordTypeId==RtAccountMBA) && (op.Customer_Type__c=='Existing Customer') &&
            (op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Project Cancelled'|| op.StageName=='Project On Hold') && 
             
             (op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
              op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
            system.debug('###################### In side Orders Won for Existing ################################');
                oplisttemp.add(op);
                ExiTotanNumberOfProjectsWon=ExiTotanNumberOfProjectsWon+1;
                if(op.Cost_band__c=='0-10L')
                {   
                    ExiTotanNumberOfProjectsWon0_10L=ExiTotanNumberOfProjectsWon0_10L+1;
                    if(op.amount != null)
                    {
                        ExiOrderWon0_10 = ExiOrderWon0_10 + op.Amount;
                    }     
                }         
                if(op.Cost_band__c=='10-50L')
                {
                    ExiTotanNumberOfProjectsWon10_50L=ExiTotanNumberOfProjectsWon10_50L+1;
                    if(op.Amount != null)
                    {
                        ExiOrderWon10_50 = ExiOrderWon10_50 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='51-150L')
                {
                    ExiTotanNumberOfProjectsWon51_150L=ExiTotanNumberOfProjectsWon51_150L+1;
                    if(op.Amount != Null)
                    {
                        ExiOrderWon51_150 = ExiOrderWon51_150 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='151-350L')
                {
                    ExiTotanNumberOfProjectsWon151_350L=ExiTotanNumberOfProjectsWon151_350L+1;
                    if(op.Amount != Null)
                    {
                        ExiOrderWon151_350 = ExiOrderWon151_350 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='351-700L')
                {
                    ExiTotanNumberOfProjectsWon351_700L=ExiTotanNumberOfProjectsWon351_700L+1;
                    if(op.Amount != Null)
                    {
                        ExiOrderWon351_700 = ExiOrderWon351_700 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='Greater than 700 L')
                {
                    ExiTotanNumberOfProjectsWonGreaterThan700L=ExiTotanNumberOfProjectsWonGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                        ExiOrderWonGreaterThan700L = ExiOrderWonGreaterThan700L + op.Amount;
                    }    
                }
                if(op.Amount != null)
                {
                    ExiOrdersWon = ExiOrdersWon + op.Amount;
                }  
            }
            
            
    //------------------------------------------------------------- for New Customer------------------------------------------------

                if((op.Account.RecordTypeId==RtAccountMBA) && (op.Customer_Type__c=='New') &&
            (op.StageName=='Order Won' || op.StageName=='Project Under Execution' || op.StageName=='Project Closed' || op.StageName=='Project Cancelled'|| op.StageName=='Project On Hold') && 
             
             (op.RecordTypeId != RtIdMBAServicesAllocated && op.RecordTypeId != RtIdMBAServicesFinal && op.RecordTypeId != RtIdMBASparesFinal &&
             
              op.RecordTypeId != RtIdPECSA && op.RecordTypeId != RtIdRegretMBARecordType && op.RecordTypeId !=RtIdSpareServicesRecordType))
            {
            system.debug('###################### In side Orders Won for New ################################');
                oplisttemp.add(op);
                NewTotanNumberOfProjectsWon=NewTotanNumberOfProjectsWon+1;
                if(op.Cost_band__c=='0-10L')
                {   
                    NewTotanNumberOfProjectsWon0_10L=NewTotanNumberOfProjectsWon0_10L+1;
                    if(op.amount != null)
                    {
                        NewOrderWon0_10 = NewOrderWon0_10 + op.Amount;
                    }     
                }         
                if(op.Cost_band__c=='10-50L')
                {
                    NewTotanNumberOfProjectsWon10_50L=NewTotanNumberOfProjectsWon10_50L+1;
                    if(op.Amount != null)
                    {
                        NewOrderWon10_50 = NewOrderWon10_50 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='51-150L')
                {
                    NewTotanNumberOfProjectsWon51_150L=NewTotanNumberOfProjectsWon51_150L+1;
                    if(op.Amount != Null)
                    {
                        NewOrderWon51_150 = NewOrderWon51_150 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='151-350L')
                {
                    NewTotanNumberOfProjectsWon151_350L=NewTotanNumberOfProjectsWon151_350L+1;
                    if(op.Amount != Null)
                    {
                        NewOrderWon151_350 = NewOrderWon151_350 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='351-700L')
                {
                    NewTotanNumberOfProjectsWon351_700L=NewTotanNumberOfProjectsWon351_700L+1;
                    if(op.Amount != Null)
                    {
                        NewOrderWon351_700 = NewOrderWon351_700 + op.Amount;
                    }
                }
                if(op.Cost_band__c=='Greater than 700 L')
                {
                    NewTotanNumberOfProjectsWonGreaterThan700L=NewTotanNumberOfProjectsWonGreaterThan700L+1;
                    if(op.Amount != null)
                    {
                        NewOrderWonGreaterThan700L = NewOrderWonGreaterThan700L + op.Amount;
                    }    
                }
                if(op.Amount != null)
                {
                    NewOrdersWon = NewOrdersWon + op.Amount;
                }  
            }
         }
        
        OrdersWon=OrdersWon/100000;
        OrderWon0_10=OrderWon0_10/100000;
        OrderWon10_50=OrderWon10_50/100000;
        OrderWon51_150=OrderWon51_150/100000;
        OrderWon151_350=OrderWon151_350/100000;
        OrderWon351_700=OrderWon351_700/100000;
        OrderWonGreaterThan700L=OrderWonGreaterThan700L/100000;
        
        ExpOrdersWon=ExpOrdersWon/100000;
        ExpOrderWon0_10=ExpOrderWon0_10/100000;
        ExpOrderWon10_50=ExpOrderWon10_50/100000;
        ExpOrderWon51_150=ExpOrderWon51_150/100000;
        ExpOrderWon151_350=ExpOrderWon151_350/100000;
        ExpOrderWon351_700=ExpOrderWon351_700/100000;
        ExpOrderWonGreaterThan700L=ExpOrderWonGreaterThan700L/100000;
        
        DomOrdersWon=DomOrdersWon/100000;
        DomOrderWon0_10=DomOrderWon0_10/100000;
        DomOrderWon10_50=DomOrderWon10_50/100000;
        DomOrderWon51_150=DomOrderWon51_150/100000;
        DomOrderWon151_350=DomOrderWon151_350/100000;
        DomOrderWon351_700=DomOrderWon351_700/100000;
        DomOrderWonGreaterThan700L=DomOrderWonGreaterThan700L/100000;
        
        ExiOrdersWon=ExiOrdersWon/100000;
        ExiOrderWon0_10=ExiOrderWon0_10/100000;
        ExiOrderWon10_50=ExiOrderWon10_50/100000;
        ExiOrderWon51_150=ExiOrderWon51_150/100000;
        ExiOrderWon151_350=ExiOrderWon151_350/100000;
        ExiOrderWon351_700=ExiOrderWon351_700/100000;
        ExiOrderWonGreaterThan700L=ExiOrderWonGreaterThan700L/100000;
        
        
        NewOrdersWon=NewOrdersWon/100000;
        NewOrderWon0_10=NewOrderWon0_10/100000;
        NewOrderWon10_50=NewOrderWon10_50/100000;
        NewOrderWon51_150=NewOrderWon51_150/100000;
        NewOrderWon151_350=NewOrderWon151_350/100000;
        NewOrderWon351_700=NewOrderWon351_700/100000;
        NewOrderWonGreaterThan700L=NewOrderWonGreaterThan700L/100000;
        
        Decimal rounded7 = Math.round(OrdersWon);
        Decimal rounded8 = Math.round(OrderWon0_10);
        Decimal rounded9 = Math.round(OrderWon10_50);
        Decimal rounded10 = Math.round(OrderWon51_150);
        Decimal rounded11 = Math.round(OrderWon151_350);
        Decimal rounded12 = Math.round(OrderWon351_700);
        Decimal rounded13 = Math.round(OrderWonGreaterThan700L);
        
       
    //---------------------------------------------------------- for calculating percentage of submitted  Vs Won----------------------------   
        if(QuotesSubmitted>0){
        
           Totalper=(OrdersWon*100)/QuotesSubmitted;
        }
        if(QuotesSubmitted0_10L>0){
        
             per0_10=(OrderWon0_10*100)/QuotesSubmitted0_10L;
        }
         if(QuotesSubmitted10_50L>0){
        
             per10_50=(OrderWon10_50*100)/QuotesSubmitted10_50L;
        }
        if(QuotesSubmitted51_150L>0){
        
             per51_150=(OrderWon51_150*100)/QuotesSubmitted51_150L;
        }
        if(QuotesSubmitted151_350L>0){
        
             per151_350=(OrderWon151_350*100)/QuotesSubmitted151_350L;
        }
        if(QuotesSubmitted351_700L>0){
        
            per351_700=(OrderWon351_700*100)/QuotesSubmitted351_700L;
        }
        if(QuotesSubmittedGreaterThan700L>0){
        
             pergtr700=(OrderWonGreaterThan700L*100)/QuotesSubmittedGreaterThan700L;
        }
      //---------------------------------------------------------percentage of no of project submitted Vs Won---------------------------
      
        if(TotanNumberOfProjects>0){
        
              NTotalper=(TotanNumberOfProjectsWon*100)/TotanNumberOfProjects;
        }
        if(TotanNumberOfProjects0_10L>0){
        
              Nper0_10=(TotanNumberOfProjectsWon0_10L*100)/TotanNumberOfProjects0_10L;
        }
        if(TotanNumberOfProjects10_50L>0){
        
              Nper10_50=(TotanNumberOfProjectsWon10_50L*100)/TotanNumberOfProjects10_50L;
        }
        if(TotanNumberOfProjects51_150L>0){
        
              Nper51_150=(TotanNumberOfProjectsWon51_150L*100)/TotanNumberOfProjects51_150L;
        }
        if(TotanNumberOfProjects151_350L>0){
        
              Nper151_350=(TotanNumberOfProjectsWon151_350L*100)/TotanNumberOfProjects151_350L;
        }
        if(TotanNumberOfProjects351_700L>0){
        
              Nper351_700=(TotanNumberOfProjectsWon351_700L*100)/TotanNumberOfProjects351_700L;
        }
        if(TotanNumberOfProjectsGreaterThan700L>0){
        
              Npergtr700=(TotanNumberOfProjectsWonGreaterThan700L*100)/TotanNumberOfProjectsGreaterThan700L;
        }
      
      
       //---------------------------------------------------------- for calculating percentage of submitted  Vs Won for Export----------------------------   
        if(ExpQuotesSubmitted>0){
        
           ExpTotalper=(ExpOrdersWon*100)/ExpQuotesSubmitted;
        }
        if(ExpQuotesSubmitted0_10L>0){
        
             Expper0_10=(ExpOrderWon0_10*100)/ExpQuotesSubmitted0_10L;
        }
         if(ExpQuotesSubmitted10_50L>0){
        
             Expper10_50=(ExpOrderWon10_50*100)/ExpQuotesSubmitted10_50L;
        }
        if(ExpQuotesSubmitted51_150L>0){
        
             Expper51_150=(ExpOrderWon51_150*100)/ExpQuotesSubmitted51_150L;
        }
        if(ExpQuotesSubmitted151_350L>0){
        
             Expper151_350=(ExpOrderWon151_350*100)/ExpQuotesSubmitted151_350L;
        }
        if(ExpQuotesSubmitted351_700L>0){
        
            Expper351_700=(ExpOrderWon351_700*100)/ExpQuotesSubmitted351_700L;
        }
        if(ExpQuotesSubmittedGreaterThan700L>0){
        
             Exppergtr700=(ExpOrderWonGreaterThan700L*100)/ExpQuotesSubmittedGreaterThan700L;
        }
      //---------------------------------------------------------percentage of no of project submitted Vs Won for Export---------------------------
      
        if(ExpTotanNumberOfProjects>0){
        
              ExpNTotalper=(ExpTotanNumberOfProjectsWon*100)/ExpTotanNumberOfProjects;
        }
        if(ExpTotanNumberOfProjects0_10L>0){
        
              ExpNper0_10=(ExpTotanNumberOfProjectsWon0_10L*100)/ExpTotanNumberOfProjects0_10L;
        }
        if(ExpTotanNumberOfProjects10_50L>0){
        
              ExpNper10_50=(ExpTotanNumberOfProjectsWon10_50L*100)/ExpTotanNumberOfProjects10_50L;
        }
        if(ExpTotanNumberOfProjects51_150L>0){
        
              ExpNper51_150=(ExpTotanNumberOfProjectsWon51_150L*100)/ExpTotanNumberOfProjects51_150L;
        }
        if(ExpTotanNumberOfProjects151_350L>0){
        
              ExpNper151_350=(ExpTotanNumberOfProjectsWon151_350L*100)/ExpTotanNumberOfProjects151_350L;
        }
        if(ExpTotanNumberOfProjects351_700L>0){
        
              ExpNper351_700=(ExpTotanNumberOfProjectsWon351_700L*100)/ExpTotanNumberOfProjects351_700L;
        }
        if(ExpTotanNumberOfProjectsGreaterThan700L>0){
        
              ExpNpergtr700=(ExpTotanNumberOfProjectsWonGreaterThan700L*100)/ExpTotanNumberOfProjectsGreaterThan700L;
        }
        
         //---------------------------------------------------------- for calculating percentage of submitted  Vs Won for Domestic----------------------------   
        if(DomQuotesSubmitted>0){
        
           DomTotalper=(DomOrdersWon*100)/DomQuotesSubmitted;
        }
        if(DomQuotesSubmitted0_10L>0){
        
             Domper0_10=(DomOrderWon0_10*100)/DomQuotesSubmitted0_10L;
        }
         if(DomQuotesSubmitted10_50L>0){
        
             Domper10_50=(DomOrderWon10_50*100)/DomQuotesSubmitted10_50L;
        }
        if(DomQuotesSubmitted51_150L>0){
        
             Domper51_150=(DomOrderWon51_150*100)/DomQuotesSubmitted51_150L;
        }
        if(DomQuotesSubmitted151_350L>0){
        
             Domper151_350=(DomOrderWon151_350*100)/DomQuotesSubmitted151_350L;
        }
        if(DomQuotesSubmitted351_700L>0){
        
            Domper351_700=(DomOrderWon351_700*100)/DomQuotesSubmitted351_700L;
        }
        if(DomQuotesSubmittedGreaterThan700L>0){
        
             Dompergtr700=(DomOrderWonGreaterThan700L*100)/DomQuotesSubmittedGreaterThan700L;
        }
      //---------------------------------------------------------percentage of no of project submitted Vs Won for Export---------------------------
      
        if(DomTotanNumberOfProjects>0){
        
              DomNTotalper=(DomTotanNumberOfProjectsWon*100)/DomTotanNumberOfProjects;
        }
        if(DomTotanNumberOfProjects0_10L>0){
        
              DomNper0_10=(DomTotanNumberOfProjectsWon0_10L*100)/DomTotanNumberOfProjects0_10L;
        }
        if(DomTotanNumberOfProjects10_50L>0){
        
              DomNper10_50=(DomTotanNumberOfProjectsWon10_50L*100)/DomTotanNumberOfProjects10_50L;
        }
        if(DomTotanNumberOfProjects51_150L>0){
        
              DomNper51_150=(DomTotanNumberOfProjectsWon51_150L*100)/DomTotanNumberOfProjects51_150L;
        }
        if(DomTotanNumberOfProjects151_350L>0){
        
              DomNper151_350=(DomTotanNumberOfProjectsWon151_350L*100)/DomTotanNumberOfProjects151_350L;
        }
        if(DomTotanNumberOfProjects351_700L>0){
        
              DomNper351_700=(DomTotanNumberOfProjectsWon351_700L*100)/DomTotanNumberOfProjects351_700L;
        }
        if(DomTotanNumberOfProjectsGreaterThan700L>0){
        
              DomNpergtr700=(DomTotanNumberOfProjectsWonGreaterThan700L*100)/DomTotanNumberOfProjectsGreaterThan700L;
        }
        
        //---------------------------------------------------------- for calculating percentage of submitted  Vs Won for Existing----------------------------   
        if(ExiQuotesSubmitted>0){
        
           ExiTotalper=(ExiOrdersWon*100)/ExiQuotesSubmitted;
        }
        if(ExiQuotesSubmitted0_10L>0){
        
             Exiper0_10=(ExiOrderWon0_10*100)/ExiQuotesSubmitted0_10L;
        }
         if(ExiQuotesSubmitted10_50L>0){
        
             Exiper10_50=(ExiOrderWon10_50*100)/ExiQuotesSubmitted10_50L;
        }
        if(ExiQuotesSubmitted51_150L>0){
        
             Exiper51_150=(ExiOrderWon51_150*100)/ExiQuotesSubmitted51_150L;
        }
        if(ExiQuotesSubmitted151_350L>0){
        
             Exiper151_350=(ExiOrderWon151_350*100)/ExiQuotesSubmitted151_350L;
        }
        if(ExiQuotesSubmitted351_700L>0){
        
            Exiper351_700=(ExiOrderWon351_700*100)/ExiQuotesSubmitted351_700L;
        }
        if(ExiQuotesSubmittedGreaterThan700L>0){
        
             Exipergtr700=(ExiOrderWonGreaterThan700L*100)/ExiQuotesSubmittedGreaterThan700L;
        }
      //---------------------------------------------------------percentage of no of project submitted Vs Won---------------------------
      
        if(ExiTotanNumberOfProjects>0){
        
              ExiNTotalper=(ExiTotanNumberOfProjectsWon*100)/ExiTotanNumberOfProjects;
        }
        if(ExiTotanNumberOfProjects0_10L>0){
        
              ExiNper0_10=(ExiTotanNumberOfProjectsWon0_10L*100)/ExiTotanNumberOfProjects0_10L;
        }
        if(ExiTotanNumberOfProjects10_50L>0){
        
              ExiNper10_50=(ExiTotanNumberOfProjectsWon10_50L*100)/ExiTotanNumberOfProjects10_50L;
        }
        if(ExiTotanNumberOfProjects51_150L>0){
        
              ExiNper51_150=(ExiTotanNumberOfProjectsWon51_150L*100)/ExiTotanNumberOfProjects51_150L;
        }
        if(ExiTotanNumberOfProjects151_350L>0){
        
              ExiNper151_350=(ExiTotanNumberOfProjectsWon151_350L*100)/ExiTotanNumberOfProjects151_350L;
        }
        if(ExiTotanNumberOfProjects351_700L>0){
        
              ExiNper351_700=(ExiTotanNumberOfProjectsWon351_700L*100)/ExiTotanNumberOfProjects351_700L;
        }
        if(ExiTotanNumberOfProjectsGreaterThan700L>0){
        
              ExiNpergtr700=(ExiTotanNumberOfProjectsWonGreaterThan700L*100)/ExiTotanNumberOfProjectsGreaterThan700L;
        }
        
        //---------------------------------------------------------- for calculating percentage of submitted  Vs Won New----------------------------   
        if(NewQuotesSubmitted>0){
        
           NewTotalper=(NewOrdersWon*100)/NewQuotesSubmitted;
        }
        if(NewQuotesSubmitted0_10L>0){
        
             Newper0_10=(NewOrderWon0_10*100)/NewQuotesSubmitted0_10L;
        }
         if(NewQuotesSubmitted10_50L>0){
        
             Newper10_50=(NewOrderWon10_50*100)/NewQuotesSubmitted10_50L;
        }
        if(NewQuotesSubmitted51_150L>0){
        
             Newper51_150=(NewOrderWon51_150*100)/NewQuotesSubmitted51_150L;
        }
        if(NewQuotesSubmitted151_350L>0){
        
             Newper151_350=(NewOrderWon151_350*100)/NewQuotesSubmitted151_350L;
        }
        if(NewQuotesSubmitted351_700L>0){
        
            Newper351_700=(NewOrderWon351_700*100)/NewQuotesSubmitted351_700L;
        }
        if(NewQuotesSubmittedGreaterThan700L>0){
        
             Newpergtr700=(NewOrderWonGreaterThan700L*100)/NewQuotesSubmittedGreaterThan700L;
        }
      //---------------------------------------------------------percentage of no of project submitted Vs Won---------------------------
      
        if(NewTotanNumberOfProjects>0){
        
              NewNTotalper=(NewTotanNumberOfProjectsWon*100)/NewTotanNumberOfProjects;
        }
        if(NewTotanNumberOfProjects0_10L>0){
        
              NewNper0_10=(NewTotanNumberOfProjectsWon0_10L*100)/NewTotanNumberOfProjects0_10L;
        }
        if(NewTotanNumberOfProjects10_50L>0){
        
              NewNper10_50=(NewTotanNumberOfProjectsWon10_50L*100)/NewTotanNumberOfProjects10_50L;
        }
        if(NewTotanNumberOfProjects51_150L>0){
        
              NewNper51_150=(NewTotanNumberOfProjectsWon51_150L*100)/NewTotanNumberOfProjects51_150L;
        }
        if(NewTotanNumberOfProjects151_350L>0){
        
              NewNper151_350=(NewTotanNumberOfProjectsWon151_350L*100)/NewTotanNumberOfProjects151_350L;
        }
        if(NewTotanNumberOfProjects351_700L>0){
        
              NewNper351_700=(NewTotanNumberOfProjectsWon351_700L*100)/NewTotanNumberOfProjects351_700L;
        }
        if(NewTotanNumberOfProjectsGreaterThan700L>0){
        
              NewNpergtr700=(NewTotanNumberOfProjectsWonGreaterThan700L*100)/NewTotanNumberOfProjectsGreaterThan700L;
        }
      
    }
    
     public void changeDateRange(){
        dateformat = false;
        //return null;
    }
    
    }