Public Class IntegrationConstants{
    public static string Lead_Industry_Automotive      = 'Automotive';
    public static string Lead_Industry_Elec            = 'Electrical & Electronics';
    public static string Lead_Industry_FMCG            = 'FMCG & Packaging'; 
    public static string Lead_Industry_Medic           = 'Medical & Healthcare'; 
    public static string Lead_Industry_GenEng          = 'General Engineering';
    public static string Lead_Industry_InterPro        = 'Internal Projects';
    public static string Lead_Industry_Solar           = 'Solar';
    public static string Lead_Industry_Other           = 'Other';
    public static Boolean isFiredAfterInsert		   = false;
    public static Boolean isAfterUpdate			   = false;
    public static Boolean isBeforeDelete              = false;
    public static Boolean isBeforeInsert              = false;
    
}