/*********************************************************************
   Class Name       : NPD_Create_New_ProjectTest
   Type             : Test Class
   Description      : This test class covers code coverage of NPD_Create_New_Project. 
   Created By       : Roshi Rai
   Created Date     : 28/11/2015
   LastModifiedby   : Keyur Modi
   LastModifiedDate : 3/12/2015  
*********************************************************************/
/*
*******************************************************************************************************************************************
ModifiedBy            Date      Tag     Description
*******************************************************************************************************************************************
Saradha(Lister)  11/15/2019   T01    Test Class Fix
*/
@isTest
Public class NPD_Create_New_ProjectTest{
    
    public static testMethod void test(){
        
    NPD_Create_New_Project objNPD = new NPD_Create_New_Project();
      
    }        
}