/*********************************************************************
   Class Name       : NPD_ProjectControllerTest
   Type             : Test Class
   Description      : This test class covers code coverage of NPD_ProjectController. 
   Created By       : Aamir Khan
   Created Date     : 01/12/2015
   LastModifiedby   : Dheeraj Gangulli
   LastModifiedDate : 04/03/2016  
*********************************************************************/
@isTest(seeAllData=false)
public class NPD_ProjectControllerTest {

    public static testMethod void testNPD_ProjectController() {
        
         NPD_ProjectController objNPD = new NPD_ProjectController();

    }  
}