/*********************************************************************
Name             : NPDCreateProjectItemsController
Description      : This class is used to create project 
Created By       : Manjula@KVP
Created Date     : 05/27/2015
LastModifiedby   : Roshi Rai/Sudama
LastModifiedDate : 11/13/2015    
REVISION HISTORY
================

Date          By                  Description
---------------------------------------------------------------

*********************************************************************/
/*
*******************************************************************************************************************************************
ModifiedBy            Date      Tag     Description
*******************************************************************************************************************************************
Saradha  11/19/2019   T01		T01- 	Hardcoded URL change fix
*/
global class NPD_ProjectController {
    
    public NPD_ProjectController(){
        
    }
}